import { StyleSheet } from "@react-pdf/renderer";
import { COLORS } from "@/lib/pdf/shared/colors";
import { REPORT_RADIUS, REPORT_SPACING, REPORT_TYPOGRAPHY } from "@/lib/pdf/shared/tokens";

export const tipPdfStyles = StyleSheet.create({
  phaseHero: {
    marginBottom: REPORT_SPACING.block,
    padding: REPORT_SPACING.cardPadding,
    borderWidth: 1,
    borderColor: COLORS.navy,
    borderRadius: REPORT_RADIUS.lg,
    backgroundColor: COLORS.surface,
  },
  phaseEyebrow: {
    fontSize: 9,
    fontFamily: "Helvetica-Bold",
    color: COLORS.navy,
    textTransform: "uppercase",
    letterSpacing: 1,
    marginBottom: 6,
  },
  phaseTitle: {
    fontSize: 20,
    fontFamily: "Helvetica-Bold",
    color: COLORS.navy,
    lineHeight: 1.25,
    marginBottom: 4,
  },
  phaseSubtitle: {
    fontSize: REPORT_TYPOGRAPHY.bodySmall,
    color: COLORS.muted,
    lineHeight: 1.5,
  },
  blockLabel: {
    fontSize: 10,
    fontFamily: "Helvetica-Bold",
    color: COLORS.navy,
    textTransform: "uppercase",
    letterSpacing: 0.7,
    marginBottom: 8,
    marginTop: 4,
  },
  bodyText: {
    fontSize: REPORT_TYPOGRAPHY.body,
    lineHeight: 1.7,
    color: COLORS.slate,
    marginBottom: 10,
  },
  callout: {
    borderWidth: 1,
    borderColor: COLORS.border,
    borderLeftWidth: 3,
    borderLeftColor: COLORS.navy,
    borderRadius: REPORT_RADIUS.md,
    backgroundColor: COLORS.surface,
    padding: REPORT_SPACING.cardPadding,
    marginBottom: REPORT_SPACING.block,
  },
  calloutTitle: {
    fontSize: 10,
    fontFamily: "Helvetica-Bold",
    color: COLORS.navy,
    marginBottom: 6,
  },
  checklistRow: {
    flexDirection: "row",
    gap: 8,
    marginBottom: 6,
    alignItems: "flex-start",
  },
  checklistMark: {
    fontSize: 11,
    fontFamily: "Helvetica-Bold",
    color: COLORS.success,
    width: 12,
    lineHeight: 1.5,
  },
  checklistText: {
    flex: 1,
    fontSize: REPORT_TYPOGRAPHY.body,
    lineHeight: 1.6,
    color: COLORS.slate,
  },
  initiativeCard: {
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: REPORT_RADIUS.lg,
    backgroundColor: COLORS.white,
    padding: REPORT_SPACING.cardPadding,
    marginBottom: REPORT_SPACING.block,
  },
  initiativeHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 12,
    marginBottom: 10,
  },
  initiativeTitle: {
    flex: 1,
    fontSize: 14,
    fontFamily: "Helvetica-Bold",
    color: COLORS.navy,
    lineHeight: 1.35,
  },
  initiativeMetaGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 12,
  },
  initiativeMetaPill: {
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: REPORT_RADIUS.sm,
    backgroundColor: COLORS.surface,
    paddingVertical: 5,
    paddingHorizontal: 8,
    minWidth: "30%",
    flexGrow: 1,
  },
  initiativeMetaLabel: {
    fontSize: 8,
    color: COLORS.muted,
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginBottom: 3,
  },
  initiativeMetaValue: {
    fontSize: 10,
    fontFamily: "Helvetica-Bold",
    color: COLORS.navy,
    lineHeight: 1.35,
  },
  initiativeFieldLabel: {
    fontSize: 9,
    fontFamily: "Helvetica-Bold",
    color: COLORS.navy,
    marginBottom: 4,
    marginTop: 6,
  },
  initiativeFieldBody: {
    fontSize: REPORT_TYPOGRAPHY.body,
    lineHeight: 1.65,
    color: COLORS.slate,
    marginBottom: 4,
  },
  maturityPanel: {
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: REPORT_RADIUS.lg,
    backgroundColor: COLORS.surface,
    padding: REPORT_SPACING.cardPadding,
    marginBottom: REPORT_SPACING.block,
  },
  pillarGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  pillarCard: {
    width: "48%",
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: REPORT_RADIUS.md,
    backgroundColor: COLORS.white,
    padding: 12,
    marginBottom: 4,
  },
  pillarCardPlanned: {
    width: "48%",
    borderWidth: 1,
    borderColor: COLORS.navy,
    borderRadius: REPORT_RADIUS.md,
    backgroundColor: COLORS.surface,
    padding: 12,
    marginBottom: 4,
  },
  roadmapStep: {
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: REPORT_RADIUS.md,
    backgroundColor: COLORS.white,
    padding: 12,
    marginBottom: 6,
  },
  roadmapStepActive: {
    borderWidth: 1,
    borderColor: COLORS.navy,
    borderRadius: REPORT_RADIUS.md,
    backgroundColor: COLORS.surface,
    padding: 12,
    marginBottom: 6,
  },
  investmentHero: {
    backgroundColor: COLORS.navy,
    borderRadius: REPORT_RADIUS.lg,
    padding: REPORT_SPACING.cardPadding,
    marginBottom: REPORT_SPACING.block,
  },
  investmentHeroSecondary: {
    backgroundColor: "#0A3D75",
    borderRadius: REPORT_RADIUS.lg,
    padding: REPORT_SPACING.cardPadding,
    marginBottom: REPORT_SPACING.block,
  },
  investmentHeroLabel: {
    fontSize: 9,
    color: "rgba(255,255,255,0.75)",
    textTransform: "uppercase",
    letterSpacing: 0.8,
    marginBottom: 6,
  },
  investmentHeroValue: {
    fontSize: 24,
    fontFamily: "Helvetica-Bold",
    color: COLORS.white,
    lineHeight: 1.1,
  },
  investmentHeroCaption: {
    fontSize: 10,
    color: "rgba(255,255,255,0.88)",
    marginTop: 8,
    lineHeight: 1.55,
  },
  nextStepRow: {
    flexDirection: "row",
    gap: 12,
    alignItems: "flex-start",
    marginBottom: 10,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: REPORT_RADIUS.md,
    padding: 12,
    backgroundColor: COLORS.white,
  },
  nextStepIndex: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: COLORS.navy,
    color: COLORS.white,
    fontSize: 10,
    fontFamily: "Helvetica-Bold",
    textAlign: "center",
    paddingTop: 4,
  },
  approvalRow: {
    flexDirection: "row",
    gap: 12,
    alignItems: "flex-start",
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: REPORT_RADIUS.md,
    backgroundColor: COLORS.surface,
    padding: 12,
    marginBottom: 10,
  },
  approvalCheckbox: {
    width: 14,
    height: 14,
    borderWidth: 1.5,
    borderColor: COLORS.navy,
    borderRadius: 3,
    marginTop: 2,
  },
  signatureLine: {
    borderBottomWidth: 1,
    borderBottomColor: COLORS.slate,
    width: 220,
    marginTop: 28,
    marginBottom: 6,
  },
  signatureLabel: {
    fontSize: REPORT_TYPOGRAPHY.bodySmall,
    color: COLORS.muted,
  },
});
