import { StyleSheet } from "@react-pdf/renderer";
import { COLORS } from "@/lib/pdf/shared/colors";
import { REPORT_RADIUS } from "@/lib/pdf/shared/tokens";
import type { ExecutivePriorityLevel, ExecutiveRiskLevel } from "@/lib/pdf/types";
import { TIP_PDF_SPACING, TIP_PDF_TYPOGRAPHY } from "@/lib/pdf/tip/tokens";

export const tipPdfStyles = StyleSheet.create({
  blockLabel: {
    fontSize: TIP_PDF_TYPOGRAPHY.label,
    fontFamily: "Helvetica-Bold",
    color: COLORS.navy,
    textTransform: "uppercase",
    letterSpacing: 0.45,
    marginBottom: 4,
    marginTop: 2,
  },
  bodyText: {
    fontSize: TIP_PDF_TYPOGRAPHY.body,
    lineHeight: 1.4,
    color: COLORS.slate,
    marginBottom: TIP_PDF_SPACING.paragraph,
  },
  callout: {
    borderWidth: 1,
    borderColor: COLORS.border,
    borderLeftWidth: 3,
    borderLeftColor: COLORS.navy,
    borderRadius: REPORT_RADIUS.md,
    backgroundColor: COLORS.surface,
    paddingVertical: TIP_PDF_SPACING.cardPaddingY,
    paddingHorizontal: TIP_PDF_SPACING.cardPaddingX,
    marginBottom: TIP_PDF_SPACING.block,
  },
  calloutTitle: {
    fontSize: TIP_PDF_TYPOGRAPHY.label,
    fontFamily: "Helvetica-Bold",
    color: COLORS.navy,
    marginBottom: 3,
  },
  scopeBox: {
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: REPORT_RADIUS.md,
    backgroundColor: COLORS.surface,
    paddingVertical: TIP_PDF_SPACING.cardPaddingY,
    paddingHorizontal: TIP_PDF_SPACING.cardPaddingX,
    marginBottom: TIP_PDF_SPACING.block,
  },
  scopeText: {
    fontSize: TIP_PDF_TYPOGRAPHY.bodySmall,
    lineHeight: 1.38,
    color: COLORS.muted,
  },
  executiveHero: {
    borderWidth: 1,
    borderColor: COLORS.navy,
    borderRadius: REPORT_RADIUS.lg,
    backgroundColor: COLORS.surface,
    paddingVertical: TIP_PDF_SPACING.cardPaddingY,
    paddingHorizontal: TIP_PDF_SPACING.cardPaddingX,
    marginBottom: TIP_PDF_SPACING.block,
  },
  executiveMetaRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
    marginBottom: 6,
  },
  executiveMetaItem: {
    minWidth: "30%",
    flexGrow: 1,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: REPORT_RADIUS.sm,
    backgroundColor: COLORS.white,
    paddingVertical: 6,
    paddingHorizontal: 7,
  },
  executiveMetaLabel: {
    fontSize: 7,
    color: COLORS.muted,
    textTransform: "uppercase",
    letterSpacing: 0.45,
    marginBottom: 2,
  },
  executiveMetaValue: {
    fontSize: 10,
    fontFamily: "Helvetica-Bold",
    color: COLORS.navy,
    lineHeight: 1.2,
  },
  kpiRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
  },
  kpiCard: {
    flex: 1,
    minWidth: "28%",
    backgroundColor: COLORS.white,
    borderRadius: REPORT_RADIUS.md,
    paddingVertical: 8,
    paddingHorizontal: 8,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  kpiCardHighlight: {
    flex: 1,
    minWidth: "28%",
    backgroundColor: COLORS.surface,
    borderRadius: REPORT_RADIUS.md,
    paddingVertical: 8,
    paddingHorizontal: 8,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  kpiLabel: {
    fontSize: TIP_PDF_TYPOGRAPHY.kpiLabel,
    color: COLORS.muted,
    textTransform: "uppercase",
    letterSpacing: 0.45,
    marginBottom: 2,
  },
  kpiValue: {
    fontSize: TIP_PDF_TYPOGRAPHY.kpiValue,
    fontFamily: "Helvetica-Bold",
    color: COLORS.navy,
    lineHeight: 1.1,
    marginBottom: 1,
  },
  kpiCaption: {
    fontSize: TIP_PDF_TYPOGRAPHY.bodySmall,
    color: COLORS.muted,
    lineHeight: 1.3,
  },
  checklistRow: {
    flexDirection: "row",
    gap: 5,
    marginBottom: 3,
    alignItems: "flex-start",
  },
  checklistMark: {
    fontSize: 8,
    fontFamily: "Helvetica-Bold",
    color: COLORS.success,
    width: 9,
    lineHeight: 1.35,
  },
  checklistText: {
    flex: 1,
    fontSize: TIP_PDF_TYPOGRAPHY.body,
    lineHeight: 1.38,
    color: COLORS.slate,
  },
  findingCard: {
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: REPORT_RADIUS.md,
    backgroundColor: COLORS.white,
    paddingVertical: TIP_PDF_SPACING.cardPaddingY,
    paddingHorizontal: TIP_PDF_SPACING.cardPaddingX,
    marginBottom: TIP_PDF_SPACING.block,
  },
  findingTitle: {
    fontSize: TIP_PDF_TYPOGRAPHY.findingTitle,
    fontFamily: "Helvetica-Bold",
    color: COLORS.navy,
    lineHeight: 1.2,
    marginBottom: TIP_PDF_SPACING.titleGap,
  },
  badgeRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: TIP_PDF_SPACING.badgeGap,
    marginBottom: TIP_PDF_SPACING.badgeToContent,
  },
  badge: {
    paddingVertical: 1.5,
    paddingHorizontal: 5,
    borderRadius: REPORT_RADIUS.sm,
    borderWidth: 1,
    fontSize: TIP_PDF_TYPOGRAPHY.badge,
    fontFamily: "Helvetica-Bold",
    textTransform: "uppercase",
    letterSpacing: 0.3,
  },
  fieldLabel: {
    fontSize: TIP_PDF_TYPOGRAPHY.label,
    fontFamily: "Helvetica-Bold",
    color: COLORS.navy,
    marginBottom: 2,
  },
  fieldBody: {
    fontSize: TIP_PDF_TYPOGRAPHY.body,
    lineHeight: 1.4,
    color: COLORS.slate,
  },
  fieldBlock: {
    marginBottom: TIP_PDF_SPACING.fieldGap,
  },
  initiativeCard: {
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: REPORT_RADIUS.md,
    backgroundColor: COLORS.white,
    paddingVertical: TIP_PDF_SPACING.cardPaddingY,
    paddingHorizontal: TIP_PDF_SPACING.cardPaddingX,
    marginBottom: TIP_PDF_SPACING.block,
  },
  initiativeTitle: {
    fontSize: TIP_PDF_TYPOGRAPHY.initiativeTitle,
    fontFamily: "Helvetica-Bold",
    color: COLORS.navy,
    marginBottom: TIP_PDF_SPACING.titleGap,
    lineHeight: 1.2,
  },
  valueMetricCard: {
    width: "48%",
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: REPORT_RADIUS.md,
    backgroundColor: COLORS.white,
    paddingVertical: 8,
    paddingHorizontal: 8,
    marginBottom: 6,
  },
  valueMetricLabel: {
    fontSize: TIP_PDF_TYPOGRAPHY.label,
    fontFamily: "Helvetica-Bold",
    color: COLORS.navy,
    marginBottom: 4,
  },
  valueMetricCompare: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 3,
  },
  valueMetricValue: {
    fontSize: TIP_PDF_TYPOGRAPHY.body,
    fontFamily: "Helvetica-Bold",
    color: COLORS.navy,
  },
  valueMetricCaption: {
    fontSize: 7,
    color: COLORS.muted,
  },
  investmentHero: {
    backgroundColor: COLORS.navy,
    borderRadius: REPORT_RADIUS.md,
    paddingVertical: TIP_PDF_SPACING.cardPaddingY,
    paddingHorizontal: TIP_PDF_SPACING.cardPaddingX,
    marginTop: 6,
    marginBottom: TIP_PDF_SPACING.block,
  },
  investmentHeroLabel: {
    fontSize: TIP_PDF_TYPOGRAPHY.label,
    color: "rgba(255,255,255,0.75)",
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginBottom: 3,
  },
  investmentHeroValue: {
    fontSize: TIP_PDF_TYPOGRAPHY.kpiValue,
    fontFamily: "Helvetica-Bold",
    color: COLORS.white,
    lineHeight: 1.1,
  },
  nextStepCard: {
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: REPORT_RADIUS.md,
    backgroundColor: COLORS.white,
    paddingVertical: TIP_PDF_SPACING.cardPaddingY,
    paddingHorizontal: TIP_PDF_SPACING.cardPaddingX,
    marginBottom: 6,
  },
  nextStepTitle: {
    fontSize: TIP_PDF_TYPOGRAPHY.body,
    fontFamily: "Helvetica-Bold",
    color: COLORS.navy,
    marginBottom: 3,
    lineHeight: 1.25,
  },
  nextStepBody: {
    fontSize: TIP_PDF_TYPOGRAPHY.body,
    lineHeight: 1.4,
    color: COLORS.slate,
  },
  tableWrap: {
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: REPORT_RADIUS.md,
    overflow: "hidden",
    marginBottom: TIP_PDF_SPACING.block,
  },
  tableHeader: {
    flexDirection: "row",
    backgroundColor: COLORS.surface,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
    paddingVertical: 4,
    paddingHorizontal: 7,
  },
  tableHeaderCell: {
    fontSize: TIP_PDF_TYPOGRAPHY.tableHeader,
    fontFamily: "Helvetica-Bold",
    color: COLORS.muted,
    textTransform: "uppercase",
    letterSpacing: 0.35,
  },
  tableRow: {
    flexDirection: "row",
    paddingVertical: 4,
    paddingHorizontal: 7,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
    backgroundColor: COLORS.white,
  },
  tableRowAlt: {
    backgroundColor: COLORS.surface,
  },
  tableCell: {
    fontSize: TIP_PDF_TYPOGRAPHY.bodySmall,
    color: COLORS.slate,
    lineHeight: 1.35,
  },
});

export const RISK_BADGE_STYLES: Record<
  ExecutiveRiskLevel,
  { bg: string; text: string; border: string }
> = {
  Low: { bg: "#ECFDF5", text: "#047857", border: "#A7F3D0" },
  Moderate: { bg: "#FFFBEB", text: "#B45309", border: "#FDE68A" },
  High: { bg: "#FFF7ED", text: "#C2410C", border: "#FED7AA" },
  Critical: { bg: "#FEF2F2", text: "#B91C1C", border: "#FECACA" },
};

export const PRIORITY_BADGE_STYLES: Record<
  ExecutivePriorityLevel,
  { bg: string; text: string; border: string }
> = {
  Immediate: { bg: "#FEF2F2", text: "#B91C1C", border: "#FECACA" },
  High: { bg: "#FFF7ED", text: "#C2410C", border: "#FED7AA" },
  Moderate: { bg: "#EFF6FF", text: "#1D4ED8", border: "#BFDBFE" },
  Planned: { bg: "#F8FAFC", text: "#475569", border: "#E2E8F0" },
};
