import type { ClientImprovementPlanDemoData } from "../types";
import {
  DemoBadge,
  DemoCard,
  DemoCardContent,
  DemoCardDescription,
  DemoCardHeader,
  DemoCardTitle,
} from "../ui/demo-primitives";
import { cn } from "../utils/cn";
import { getScoreBarColorClass, getScoreTextColorClass } from "../utils/score-display";

type ExecutiveReportDemoProps = {
  data: ClientImprovementPlanDemoData;
};

const readinessVariant = {
  ready: "success",
  "in-progress": "warning",
  planned: "outline",
} as const;

export function ExecutiveReportDemo({ data }: ExecutiveReportDemoProps) {
  return (
    <div className="space-y-6">
      <DemoCard className="border-primary/20 bg-primary/5">
        <DemoCardHeader>
          <DemoCardTitle>Executive Report Preview</DemoCardTitle>
          <DemoCardDescription>
            Client-safe preview of the Technology Improvement Plan report for {data.clientName}.
          </DemoCardDescription>
        </DemoCardHeader>
        <DemoCardContent>
          <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
            <Metric label="Current score" value={data.currentScore} score />
            <Metric label="Projected score" value={data.projectedScore} score />
            <Metric label="Expected improvement" value={`+${data.expectedImprovement}`} />
            <Metric label="Estimated timeline" value={data.estimatedTimeline} />
            <Metric label="Technology maturity level" value={data.maturityLevel} />
            <Metric label="Overall risk reduction" value={data.overallRiskReduction} />
            <Metric label="Business readiness" value={data.businessReadiness} />
          </div>
        </DemoCardContent>
      </DemoCard>

      <div className="overflow-hidden rounded-xl border border-border/70 bg-[#06111f] shadow-sm">
        <div className="bg-[#082f5b] px-5 py-8 text-white sm:px-8">
          <p className="text-xs font-semibold uppercase tracking-[0.18em] text-sky-200">
            Generated by StackScore
          </p>
          <h3 className="mt-3 text-2xl font-semibold tracking-tight sm:text-3xl">
            Technology Improvement Plan
          </h3>
          <p className="mt-2 max-w-2xl text-sm text-sky-100/90">
            A phased roadmap to strengthen technology maturity and reduce preventable risk.
          </p>
          <div className="mt-6 grid gap-4 sm:grid-cols-3">
            <CoverMeta label="Prepared for" value={data.clientName} />
            <CoverMeta label="Based on assessment" value={data.assessmentName} />
            <CoverMeta label="Implementation timeline" value={data.estimatedTimeline} />
          </div>
        </div>

        <div className="space-y-5 bg-card px-5 py-6 sm:px-8">
          <div className="grid gap-4 md:grid-cols-[1fr_auto_1fr] md:items-center">
            <ScorePanel label="Today" score={data.currentScore} />
            <div className="text-center">
              <p className="text-2xl font-semibold text-primary">+{data.expectedImprovement}</p>
              <p className="text-xs text-muted-foreground">StackScore points</p>
            </div>
            <ScorePanel label="Projected" score={data.projectedScore} />
          </div>

          <div className="rounded-lg border bg-background p-4">
            <h4 className="text-sm font-medium">Executive Summary</h4>
            <p className="mt-2 text-sm leading-relaxed text-muted-foreground">
              {data.executiveSummary}
            </p>
          </div>
        </div>
      </div>

      <DemoCard>
        <DemoCardHeader>
          <DemoCardTitle>Report section readiness</DemoCardTitle>
          <DemoCardDescription>
            Sections included in the client-facing executive report.
          </DemoCardDescription>
        </DemoCardHeader>
        <DemoCardContent>
          <div className="grid gap-3 md:grid-cols-2">
            {data.reportSections.map((section) => (
              <div
                key={section.id}
                className="rounded-lg border bg-background p-3"
              >
                <div className="flex flex-wrap items-center justify-between gap-2">
                  <p className="text-sm font-medium">{section.title}</p>
                  <DemoBadge variant={readinessVariant[section.readiness]}>
                    {section.readiness === "in-progress" ? "In progress" : section.readiness}
                  </DemoBadge>
                </div>
                <p className="mt-2 text-sm text-muted-foreground">{section.summary}</p>
              </div>
            ))}
          </div>
        </DemoCardContent>
      </DemoCard>
    </div>
  );
}

function Metric({
  label,
  value,
  score = false,
}: {
  label: string;
  value: string | number;
  score?: boolean;
}) {
  return (
    <div className="rounded-lg border bg-background p-3">
      <p className="text-xs text-muted-foreground">{label}</p>
      <p
        className={cn(
          "mt-1 text-lg font-semibold tabular-nums",
          score && typeof value === "number" ? getScoreTextColorClass(value) : undefined,
        )}
      >
        {value}
      </p>
    </div>
  );
}

function CoverMeta({ label, value }: { label: string; value: string }) {
  return (
    <div>
      <p className="text-xs uppercase tracking-wide text-sky-200/80">{label}</p>
      <p className="mt-1 text-sm font-medium text-white">{value}</p>
    </div>
  );
}

function ScorePanel({ label, score }: { label: string; score: number }) {
  return (
    <div className="rounded-lg border bg-background p-4">
      <p className="text-xs text-muted-foreground">{label}</p>
      <p className={cn("mt-1 text-3xl font-semibold tabular-nums", getScoreTextColorClass(score))}>
        {score}
      </p>
      <div className="mt-3 h-2 overflow-hidden rounded-full bg-muted">
        <div
          className={cn("h-full rounded-full", getScoreBarColorClass(score))}
          style={{ width: `${Math.min(100, score)}%` }}
        />
      </div>
    </div>
  );
}
