import type { LucideIcon } from "lucide-react";
import { TrendingUp } from "lucide-react";
import { BRAND } from "@/lib/branding";
import { cn } from "@/lib/utils";

type ReportFooterProps = {
  icon?: LucideIcon;
  className?: string;
  confidentialFor?: string;
};

export function ReportFooter({
  icon: Icon = TrendingUp,
  className,
  confidentialFor,
}: ReportFooterProps) {
  return (
    <div
      className={cn(
        "border-t pt-6 text-center text-xs text-muted-foreground print:pt-4",
        className,
      )}
    >
      <Icon className="mx-auto mb-2 h-4 w-4" />
      {confidentialFor ? (
        <p className="mb-2 leading-relaxed">
          CONFIDENTIAL — Prepared exclusively for {confidentialFor} by {BRAND.companyName}.
        </p>
      ) : null}
      <p>
        Generated by {BRAND.productName} · {BRAND.companyName}
      </p>
    </div>
  );
}
