import { BRAND } from "@/lib/branding";
import { getReportTypeMeta } from "@/lib/reports/meta";
import type { ReportType } from "@/lib/reports/types";
import { cn } from "@/lib/utils";

type ReportCoverProps = {
  reportType: ReportType;
  title?: string;
  subtitle?: string;
  className?: string;
};

export function ReportCover({ reportType, title, subtitle, className }: ReportCoverProps) {
  const meta = getReportTypeMeta(reportType);
  const attribution =
    meta.attribution === "prepared"
      ? `Prepared by ${BRAND.companyName}`
      : `Generated by ${BRAND.productName}`;

  return (
    <div
      className={cn(
        "report-cover bg-primary px-8 py-10 text-primary-foreground print:break-after-page",
        className,
      )}
    >
      <p className="text-xs uppercase tracking-[0.2em] text-primary-foreground/70">
        {attribution}
      </p>
      <h3 className="mt-2 text-3xl font-bold tracking-tight">{title ?? meta.title}</h3>
      <p className="mt-3 max-w-3xl text-sm leading-relaxed text-primary-foreground/85">
        {subtitle ?? meta.subtitle}
      </p>
    </div>
  );
}
