import type { ClientWorkspaceSnapshot } from "@/lib/client-workspace";
import type { TechnologyProfileDetail } from "@/lib/technology-profile/types";

export const CLIENT_DASHBOARD_PREVIEW_CLIENT_ID = "preview-pinnacle-engineering";

const PINNACLE_TECHNOLOGY_VISION =
  "Pinnacle Engineering is a growing civil and structural engineering firm with 84 employees across two offices. The organization relies on Microsoft 365 Business Premium, hybrid Entra ID, Ubiquiti networking, NinjaOne RMM, Synology backup, and Azure-hosted line-of-business applications.";

const previewWorkspace: ClientWorkspaceSnapshot = {
  kpis: {
    stackScore: 53,
    projectedScore: 84,
    openProjectsCount: 4,
    criticalRecommendationsCount: 7,
    immediateFocusCount: 7,
  },
  items: [
    {
      id: "preview-focus-1",
      kind: "project",
      title: "Implement centralized endpoint management",
      pillarName: "Endpoint Management",
      priority: "critical",
      estimatedImpactPoints: 6,
      statusLabel: "In Progress",
      readinessLabel: "Ready",
      sourceLabel: "From recommendation",
      href: "#",
    },
    {
      id: "preview-focus-2",
      kind: "recommendation",
      title: "Deploy infrastructure availability monitoring",
      pillarName: "Security Operations",
      priority: "critical",
      estimatedImpactPoints: 5,
      statusLabel: "Accepted",
      readinessLabel: "Ready",
      sourceLabel: "Recommendation",
      href: "#",
    },
    {
      id: "preview-focus-3",
      kind: "project",
      title: "Standardize Microsoft 365 security baseline",
      pillarName: "Productivity & Collaboration",
      priority: "critical",
      estimatedImpactPoints: 5,
      statusLabel: "In Progress",
      readinessLabel: "Ready",
      sourceLabel: "From recommendation",
      href: "#",
    },
    {
      id: "preview-focus-4",
      kind: "recommendation",
      title: "Establish immutable backup strategy",
      pillarName: "Data Protection & Recovery",
      priority: "critical",
      estimatedImpactPoints: 6,
      statusLabel: "Accepted",
      readinessLabel: "Ready",
      sourceLabel: "Recommendation",
      href: "#",
    },
    {
      id: "preview-focus-5",
      kind: "recommendation",
      title: "Formalize vendor lifecycle documentation",
      pillarName: "Technology Strategy",
      priority: "critical",
      estimatedImpactPoints: 4,
      statusLabel: "Open",
      readinessLabel: "Ready",
      sourceLabel: "Recommendation",
      href: "#",
    },
  ],
};

/** Static demo profile for public marketing previews — never loaded from the database. */
export const CLIENT_DASHBOARD_PREVIEW_DETAIL: TechnologyProfileDetail = {
  profile: {
    id: "preview-profile",
    clientId: CLIENT_DASHBOARD_PREVIEW_CLIENT_ID,
    overallStackScore: 53,
    maturityTier: "developing",
    maturityTierLabel: "Developing",
    categoryScores: [],
    pillarSnapshots: null,
    scoringEngineVersion: "v2",
    v1CategoryScores: [],
    riskSummary: {
      critical: 7,
      high: 4,
      medium: 6,
      low: 2,
      criticalExposure: true,
    },
    trendDirection: "improving",
    lastAssessedAt: "2026-06-21T00:00:00.000Z",
    nextRecommendedAssessmentAt: "2026-12-15T00:00:00.000Z",
    currentAssessmentId: "preview-assessment",
    openRecommendationCount: 12,
    criticalExposureCount: 7,
  },
  client: {
    id: CLIENT_DASHBOARD_PREVIEW_CLIENT_ID,
    companyName: "Pinnacle Engineering",
    primaryContactName: "Jordan Ellis",
    primaryContactEmail: "jordan.ellis@pinnacle-engineering.example",
    industry: "Engineering",
    status: "active",
  },
  scoreTrend: [],
  openRecommendations: [],
  activeProjects: [],
  completedProjects: [],
  journey: {
    phase: "improve",
    phaseLabel: "Improve",
    assessmentsCompleted: 2,
    openRecommendations: 12,
    activeProjects: 4,
    completedProjects: 1,
    scoreDelta: 8,
    progressPercent: 42,
  },
  audience: "internal",
  capabilities: {
    canEditBusinessProfile: false,
    canEditImprovementPlan: false,
    canViewPricing: false,
    canViewInternalDocuments: false,
  },
  businessSnapshot: {
    industry: "Engineering",
    employeeCount: 84,
    numberOfLocations: 2,
    primaryBusinessGoal: "improve_cybersecurity",
    primaryBusinessGoalLabel: "Improve Cybersecurity",
    technologyVision: PINNACLE_TECHNOLOGY_VISION,
    itSupportModel: "msp",
    itSupportModelLabel: "Managed Service Provider",
    environmentType: "hybrid",
    environmentTypeLabel: "Hybrid",
    complianceFramework: null,
    complianceFrameworkLabel: "—",
    complianceStatus: null,
    primaryContactName: "Jordan Ellis",
    primaryContactTitle: "Director of Operations",
    primaryContactEmail: "jordan.ellis@pinnacle-engineering.example",
    primaryContactPhone: null,
  },
  journeyScores: {
    initialScore: 45,
    currentScore: 53,
    projectedScore: 84,
    longTermTargetScore: 90,
    scoreDeltaSincePrevious: 8,
    scoreDeltaSinceInitial: 8,
  },
  nextAction: {
    label: "Review recommendations",
    description: "Prioritize the next improvement initiative.",
    href: "#",
    kind: "recommendations",
  },
  categoryInsights: [],
  pillarInsights: [],
  roadmapPreview: [],
  documents: [],
  activeTip: null,
  scoreDeltaSincePrevious: 8,
  sections: {
    showAssessmentForms: false,
    showAdminActions: false,
    showBusinessSnapshot: true,
    showBusinessSnapshotLimited: false,
    showOpenOpportunities: false,
    showRoadmapPreview: false,
    showRecentProgress: false,
    showActiveProjects: false,
    showAssessmentResultsLink: false,
    showRoadmapBuilderLink: false,
    showNextActionCta: false,
    showRecommendationCounts: false,
    showJourneyTimeline: false,
    showRecommendationsLink: false,
  },
  journeyTimeline: [],
  workspace: previewWorkspace,
  draftAssessmentId: null,
};
