import type { PortfolioExecutiveReportData } from "../types";
import { portfolioPreviewData } from "../data/preview-data";
import {
  PreviewBadge,
  PreviewCard,
  PreviewCardContent,
  PreviewCardDescription,
  PreviewCardHeader,
  PreviewCardTitle,
  PreviewShell,
} from "./portfolio-primitives";
import { cn } from "./cn";
import { getScoreBarColorClass, getScoreTextColorClass } from "./score-display";

export type ExecutiveReportPreviewProps = {
  data?: PortfolioExecutiveReportData;
  className?: string;
  brandCompanyName?: string;
  brandProductName?: string;
};

export function ExecutiveReportPreview({
  data = portfolioPreviewData.executiveReport,
  brandCompanyName = portfolioPreviewData.brandCompanyName,
  brandProductName = portfolioPreviewData.brandProductName,
  className,
}: ExecutiveReportPreviewProps) {
  return (
    <PreviewShell className={cn("space-y-5 p-4 sm:p-6", className)}>
      <div className="overflow-hidden rounded-xl border border-slate-200 shadow-sm dark:border-slate-700">
        <div className="bg-[#082f5b] px-5 py-8 text-white sm:px-8">
          <p className="text-xs font-semibold uppercase tracking-[0.18em] text-sky-200">
            Generated by {brandProductName}
          </p>
          <h3 className="mt-3 text-2xl font-semibold tracking-tight sm:text-3xl">
            {data.documentTitle}
          </h3>
          <p className="mt-2 max-w-2xl text-sm text-sky-100/90">{data.documentSubtitle}</p>
          <div className="mt-6 grid gap-4 sm:grid-cols-3">
            <CoverMeta label="Prepared for" value={data.organizationName} />
            <CoverMeta label="Review period" value={data.reviewPeriod} />
            <CoverMeta label="Generated" value={data.generatedDate} />
          </div>
          <p className="mt-6 text-xs text-sky-100/80">
            Prepared by {brandCompanyName}. Confidential sample for portfolio demonstration.
          </p>
        </div>

        <div className="space-y-5 bg-white px-5 py-6 dark:bg-slate-900 sm:px-8">
          <div className="grid gap-4 md:grid-cols-[1fr_auto_1fr] md:items-center">
            <ScorePanel label="Today" score={data.currentScore} />
            <div className="text-center">
              <p className="text-2xl font-semibold text-sky-700 dark:text-sky-400">
                +{data.expectedImprovement}
              </p>
              <p className="text-xs text-slate-500 dark:text-slate-400">StackScore points</p>
            </div>
            <ScorePanel label="Projected" score={data.projectedScore} />
          </div>

          <div className="grid gap-3 sm:grid-cols-3">
            <Metric label="Maturity level" value={data.maturityLabel} />
            <Metric label="Risk reduction" value={data.riskReduction} />
            <Metric label="Business readiness" value={data.businessReadiness} />
          </div>

          <div className="rounded-lg border border-slate-200 bg-slate-50 p-4 dark:border-slate-700 dark:bg-slate-950/40">
            <h4 className="text-sm font-medium">Executive Summary</h4>
            <p className="mt-2 text-sm leading-relaxed text-slate-600 dark:text-slate-300">
              {data.executiveSummary}
            </p>
          </div>
        </div>
      </div>

      <PreviewCard>
        <PreviewCardHeader>
          <PreviewCardTitle>Report sections</PreviewCardTitle>
          <PreviewCardDescription>
            Client facing sections included in the executive deliverable.
          </PreviewCardDescription>
        </PreviewCardHeader>
        <PreviewCardContent>
          <div className="grid gap-3 md:grid-cols-2">
            {data.sections.map((section) => (
              <div
                key={section.id}
                className="rounded-lg border border-slate-200 bg-slate-50 p-3 dark:border-slate-700 dark:bg-slate-950/40"
              >
                <div className="flex flex-wrap items-center justify-between gap-2">
                  <p className="text-sm font-medium">{section.title}</p>
                  <PreviewBadge className="border-emerald-200 bg-emerald-50 text-emerald-800 dark:border-emerald-900 dark:bg-emerald-950/40 dark:text-emerald-300">
                    Ready
                  </PreviewBadge>
                </div>
                <p className="mt-2 text-sm text-slate-600 dark:text-slate-400">{section.summary}</p>
              </div>
            ))}
          </div>
        </PreviewCardContent>
      </PreviewCard>
    </PreviewShell>
  );
}

function CoverMeta({ label, value }: { label: string; value: string }) {
  return (
    <div>
      <p className="text-xs uppercase tracking-wide text-sky-200/80">{label}</p>
      <p className="mt-1 text-sm font-medium text-white">{value}</p>
    </div>
  );
}

function Metric({ label, value }: { label: string; value: string }) {
  return (
    <div className="rounded-lg border border-slate-200 bg-slate-50 p-3 dark:border-slate-700 dark:bg-slate-950/40">
      <p className="text-xs text-slate-500 dark:text-slate-400">{label}</p>
      <p className="mt-1 text-sm font-semibold">{value}</p>
    </div>
  );
}

function ScorePanel({ label, score }: { label: string; score: number }) {
  return (
    <div className="rounded-lg border border-slate-200 bg-slate-50 p-4 dark:border-slate-700 dark:bg-slate-950/40">
      <p className="text-xs text-slate-500 dark:text-slate-400">{label}</p>
      <p className={cn("mt-1 text-3xl font-semibold tabular-nums", getScoreTextColorClass(score))}>
        {score}
      </p>
      <div className="mt-3 h-2 overflow-hidden rounded-full bg-slate-200 dark:bg-slate-800">
        <div
          className={cn("h-full rounded-full", getScoreBarColorClass(score))}
          style={{ width: `${Math.min(100, score)}%` }}
        />
      </div>
    </div>
  );
}
