import type { ResponseType } from "@/generated/prisma/client";

export type QuestionLibraryMetadata = {
  code: string;
  v2QuestionId: string;
  v2Category: string;
  capability: string;
  purpose: string;
  responseType: ResponseType;
  evidenceRequired: string;
  relatedService?: string;
  relatedPlaybook?: string;
  relatedTechnologies?: string[];
  adminNotes?: string;
};

type MetaInput = Omit<QuestionLibraryMetadata, "code"> & { code: string };

function meta(entry: MetaInput): QuestionLibraryMetadata {
  return entry;
}

/** DOC-114-aligned metadata for Q01–Q50 (v1 bank). Source of truth for seed + validation. */
export const QUESTION_LIBRARY_METADATA: QuestionLibraryMetadata[] = [
  meta({ code: "Q01", v2QuestionId: "SEC-001", v2Category: "security", capability: "Multi-Factor Authentication", purpose: "Evaluate identity protection for Microsoft 365 users.", responseType: "ternary", evidenceRequired: "Entra ID MFA report or admin portal confirmation.", relatedService: "MFA Deployment", relatedPlaybook: "Cybersecurity", relatedTechnologies: ["Microsoft Entra ID", "Cisco Duo"] }),
  meta({ code: "Q02", v2QuestionId: "SEC-002", v2Category: "security", capability: "Privileged Access Protection", purpose: "Evaluate MFA enforcement on administrative accounts.", responseType: "ternary", evidenceRequired: "Admin account MFA status from identity provider.", relatedService: "MFA Deployment", relatedPlaybook: "Cybersecurity" }),
  meta({ code: "Q03", v2QuestionId: "SEC-003", v2Category: "security", capability: "Endpoint Protection", purpose: "Evaluate endpoint security agent deployment coverage.", responseType: "ternary", evidenceRequired: "RMM or EDR deployment report.", relatedService: "Endpoint Security Management", relatedPlaybook: "Cybersecurity", relatedTechnologies: ["SentinelOne", "CrowdStrike", "Microsoft Defender"] }),
  meta({ code: "Q04", v2QuestionId: "SEC-004", v2Category: "security", capability: "Security Monitoring", purpose: "Evaluate active monitoring of endpoint protection.", responseType: "ternary", evidenceRequired: "SOC or RMM alert configuration review.", relatedService: "Managed Endpoint Security", relatedPlaybook: "Cybersecurity" }),
  meta({ code: "Q05", v2QuestionId: "SEC-005", v2Category: "security", capability: "Patch Management", purpose: "Evaluate centralized operating system update management.", responseType: "ternary", evidenceRequired: "WSUS, Intune, or RMM patch policy screenshot.", relatedService: "Patch Management Services", relatedPlaybook: "Cybersecurity" }),
  meta({ code: "Q06", v2QuestionId: "SEC-006", v2Category: "security", capability: "Vulnerability Management", purpose: "Evaluate timely installation of critical security patches.", responseType: "ternary", evidenceRequired: "Patch compliance report within 30-day window.", relatedService: "Patch Management Services", relatedPlaybook: "Cybersecurity" }),
  meta({ code: "Q07", v2QuestionId: "SEC-007", v2Category: "security", capability: "Email Security", purpose: "Evaluate advanced email threat protection.", responseType: "ternary", evidenceRequired: "Microsoft 365 Defender or third-party filter configuration.", relatedService: "Microsoft 365 Security & Protection", relatedPlaybook: "Cybersecurity" }),
  meta({ code: "Q08", v2QuestionId: "SEC-008", v2Category: "security", capability: "Security Awareness", purpose: "Evaluate phishing awareness training cadence.", responseType: "ternary", evidenceRequired: "Training completion records or vendor report.", relatedService: "Security Awareness Training", relatedPlaybook: "Cybersecurity" }),
  meta({ code: "Q09", v2QuestionId: "SEC-009", v2Category: "security", capability: "User Lifecycle Management", purpose: "Evaluate periodic user account access reviews.", responseType: "ternary", evidenceRequired: "Access review documentation or audit log.", relatedService: "Identity Management", relatedPlaybook: "Cybersecurity" }),
  meta({ code: "Q10", v2QuestionId: "SEC-010", v2Category: "security", capability: "User Offboarding", purpose: "Evaluate immediate account deactivation upon termination.", responseType: "ternary", evidenceRequired: "HR offboarding procedure and recent examples.", relatedService: "Identity Management", relatedPlaybook: "Cybersecurity" }),
  meta({ code: "Q11", v2QuestionId: "BCP-001", v2Category: "business_continuity", capability: "Server Backup", purpose: "Evaluate server backup coverage.", responseType: "ternary", evidenceRequired: "Backup job report or BDR console screenshot.", relatedService: "Backup & Disaster Recovery", relatedPlaybook: "Business Continuity" }),
  meta({ code: "Q12", v2QuestionId: "BCP-002", v2Category: "business_continuity", capability: "Workstation Backup", purpose: "Evaluate critical workstation backup coverage.", responseType: "ternary", evidenceRequired: "Endpoint backup agent deployment report.", relatedService: "Backup & Disaster Recovery", relatedPlaybook: "Business Continuity" }),
  meta({ code: "Q13", v2QuestionId: "BCP-003", v2Category: "business_continuity", capability: "Cloud Data Protection", purpose: "Evaluate independent Microsoft 365 data backup.", responseType: "ternary", evidenceRequired: "M365 backup vendor dashboard or retention policy.", relatedService: "Microsoft 365 Backup", relatedPlaybook: "Business Continuity" }),
  meta({ code: "Q14", v2QuestionId: "BCP-004", v2Category: "business_continuity", capability: "Backup Validation", purpose: "Evaluate backup restore testing within 90 days.", responseType: "ternary", evidenceRequired: "Restore test log or ticket documentation.", relatedService: "Backup & Disaster Recovery", relatedPlaybook: "Business Continuity" }),
  meta({ code: "Q15", v2QuestionId: "BCP-005", v2Category: "business_continuity", capability: "Recovery Validation", purpose: "Evaluate successful full restore capability.", responseType: "ternary", evidenceRequired: "Documented restore test results.", relatedService: "Backup & Disaster Recovery", relatedPlaybook: "Business Continuity" }),
  meta({ code: "Q16", v2QuestionId: "BCP-006", v2Category: "business_continuity", capability: "Offsite Backup Storage", purpose: "Evaluate offsite or immutable backup storage.", responseType: "ternary", evidenceRequired: "Backup storage architecture diagram or vendor config.", relatedService: "Backup & Disaster Recovery", relatedPlaybook: "Business Continuity" }),
  meta({ code: "Q17", v2QuestionId: "BCP-007", v2Category: "business_continuity", capability: "Ransomware Resilience", purpose: "Evaluate backup protection from ransomware and deletion.", responseType: "ternary", evidenceRequired: "Immutable storage or air-gap configuration evidence.", relatedService: "Backup & Disaster Recovery", relatedPlaybook: "Business Continuity" }),
  meta({ code: "Q18", v2QuestionId: "BCP-008", v2Category: "business_continuity", capability: "Backup Monitoring", purpose: "Evaluate backup failure monitoring and review.", responseType: "ternary", evidenceRequired: "Alert configuration or weekly backup review log.", relatedService: "Managed Backup Monitoring", relatedPlaybook: "Business Continuity" }),
  meta({ code: "Q19", v2QuestionId: "INF-001", v2Category: "infrastructure", capability: "Firewall Lifecycle", purpose: "Evaluate primary firewall age and lifecycle status.", responseType: "ternary", evidenceRequired: "Asset inventory or firewall serial/model documentation.", relatedService: "Network Infrastructure", relatedPlaybook: "Infrastructure Modernization" }),
  meta({ code: "Q20", v2QuestionId: "INF-002", v2Category: "infrastructure", capability: "Switch Lifecycle", purpose: "Evaluate network switch age and lifecycle status.", responseType: "ternary", evidenceRequired: "Network equipment inventory.", relatedService: "Network Infrastructure", relatedPlaybook: "Infrastructure Modernization" }),
  meta({ code: "Q21", v2QuestionId: "INF-003", v2Category: "infrastructure", capability: "Wireless Coverage", purpose: "Evaluate wireless network coverage adequacy.", responseType: "ternary", evidenceRequired: "Site survey or user coverage feedback.", relatedService: "Wireless Networking", relatedPlaybook: "Infrastructure Modernization" }),
  meta({ code: "Q22", v2QuestionId: "INF-004", v2Category: "infrastructure", capability: "Power Protection", purpose: "Evaluate UPS protection for critical systems.", responseType: "ternary", evidenceRequired: "UPS inventory and maintenance records.", relatedService: "Infrastructure Services", relatedPlaybook: "Infrastructure Modernization" }),
  meta({ code: "Q23", v2QuestionId: "INF-005", v2Category: "infrastructure", capability: "Internet Redundancy", purpose: "Evaluate internet connection redundancy.", responseType: "ternary", evidenceRequired: "ISP contract or failover configuration.", relatedService: "Network Infrastructure", relatedPlaybook: "Infrastructure Modernization" }),
  meta({ code: "Q24", v2QuestionId: "INF-006", v2Category: "infrastructure", capability: "Network Monitoring", purpose: "Evaluate active network equipment monitoring.", responseType: "ternary", evidenceRequired: "NMS or RMM monitoring dashboard.", relatedService: "Managed Network Services", relatedPlaybook: "Infrastructure Modernization" }),
  meta({ code: "Q25", v2QuestionId: "INF-007", v2Category: "infrastructure", capability: "Network Segmentation", purpose: "Evaluate guest and business network separation.", responseType: "ternary", evidenceRequired: "Network diagram showing VLAN or SSID separation.", relatedService: "Network Security", relatedPlaybook: "Cybersecurity" }),
  meta({ code: "Q26", v2QuestionId: "OPS-001", v2Category: "operations", capability: "Asset Inventory", purpose: "Evaluate completeness of device inventory.", responseType: "ternary", evidenceRequired: "RMM or asset management export.", relatedService: "Endpoint Management", relatedPlaybook: "Operations Excellence" }),
  meta({ code: "Q27", v2QuestionId: "OPS-002", v2Category: "operations", capability: "Endpoint Management", purpose: "Evaluate centralized endpoint management.", responseType: "ternary", evidenceRequired: "MDM or RMM enrollment report.", relatedService: "Endpoint Management", relatedPlaybook: "Operations Excellence" }),
  meta({ code: "Q28", v2QuestionId: "OPS-003", v2Category: "operations", capability: "Remote Support", purpose: "Evaluate remote support capability for endpoints.", responseType: "ternary", evidenceRequired: "Remote support tool deployment status.", relatedService: "Managed IT Support", relatedPlaybook: "Operations Excellence" }),
  meta({ code: "Q29", v2QuestionId: "OPS-004", v2Category: "operations", capability: "Warranty Tracking", purpose: "Evaluate device warranty tracking practices.", responseType: "ternary", evidenceRequired: "Asset register with warranty dates.", relatedService: "Endpoint Management", relatedPlaybook: "Operations Excellence" }),
  meta({ code: "Q30", v2QuestionId: "OPS-005", v2Category: "operations", capability: "Hardware Lifecycle", purpose: "Evaluate defined hardware replacement cycle.", responseType: "ternary", evidenceRequired: "Lifecycle policy or refresh schedule.", relatedService: "Technology Lifecycle Management", relatedPlaybook: "Operations Excellence" }),
  meta({ code: "Q31", v2QuestionId: "OPS-006", v2Category: "operations", capability: "Operating System Support", purpose: "Evaluate presence of unsupported operating systems.", responseType: "ternary", evidenceRequired: "OS inventory report from RMM.", relatedService: "Endpoint Management", relatedPlaybook: "Operations Excellence" }),
  meta({ code: "Q32", v2QuestionId: "OPS-007", v2Category: "operations", capability: "Endpoint Health Monitoring", purpose: "Evaluate device health and performance monitoring.", responseType: "ternary", evidenceRequired: "RMM health dashboard or alert configuration.", relatedService: "Managed Endpoint Services", relatedPlaybook: "Operations Excellence" }),
  meta({ code: "Q33", v2QuestionId: "DOC-001", v2Category: "documentation", capability: "Network Documentation", purpose: "Evaluate currency of network diagram documentation.", responseType: "ternary", evidenceRequired: "Current network diagram with revision date.", relatedService: "Documentation Services", relatedPlaybook: "Operational Readiness" }),
  meta({ code: "Q34", v2QuestionId: "DOC-002", v2Category: "documentation", capability: "Vendor Documentation", purpose: "Evaluate vendor contact documentation.", responseType: "ternary", evidenceRequired: "Vendor contact list or IT binder.", relatedService: "Documentation Services", relatedPlaybook: "Operational Readiness" }),
  meta({ code: "Q35", v2QuestionId: "DOC-003", v2Category: "documentation", capability: "Credential Management", purpose: "Evaluate secure storage of administrative credentials.", responseType: "ternary", evidenceRequired: "Password manager or vault usage confirmation.", relatedService: "Security Hardening Services", relatedPlaybook: "Cybersecurity" }),
  meta({ code: "Q36", v2QuestionId: "DOC-004", v2Category: "documentation", capability: "IT Procedures", purpose: "Evaluate documentation of critical IT procedures.", responseType: "ternary", evidenceRequired: "IT procedure binder or knowledge base.", relatedService: "Documentation Services", relatedPlaybook: "Operational Readiness" }),
  meta({ code: "Q37", v2QuestionId: "DOC-005", v2Category: "documentation", capability: "Employee Onboarding", purpose: "Evaluate documented employee onboarding procedure.", responseType: "ternary", evidenceRequired: "HR/IT onboarding checklist.", relatedService: "Documentation Services", relatedPlaybook: "Operational Readiness" }),
  meta({ code: "Q38", v2QuestionId: "DOC-006", v2Category: "documentation", capability: "Employee Offboarding", purpose: "Evaluate documented employee offboarding procedure.", responseType: "ternary", evidenceRequired: "HR/IT offboarding checklist.", relatedService: "Documentation Services", relatedPlaybook: "Operational Readiness" }),
  meta({ code: "Q39", v2QuestionId: "DOC-007", v2Category: "documentation", capability: "License Management", purpose: "Evaluate software licensing tracking.", responseType: "ternary", evidenceRequired: "License inventory or SAM tool export.", relatedService: "Documentation Services", relatedPlaybook: "Operational Readiness" }),
  meta({ code: "Q40", v2QuestionId: "BCP-009", v2Category: "business_continuity", capability: "Disaster Recovery Planning", purpose: "Evaluate existence of documented disaster recovery plan.", responseType: "ternary", evidenceRequired: "DR plan document with revision date.", relatedService: "Business Continuity Planning", relatedPlaybook: "Business Continuity" }),
  meta({ code: "Q41", v2QuestionId: "BCP-010", v2Category: "business_continuity", capability: "DR Testing", purpose: "Evaluate disaster recovery plan testing cadence.", responseType: "ternary", evidenceRequired: "DR test results or tabletop exercise records.", relatedService: "Business Continuity Planning", relatedPlaybook: "Business Continuity" }),
  meta({ code: "Q42", v2QuestionId: "BCP-011", v2Category: "business_continuity", capability: "Remote Work Continuity", purpose: "Evaluate remote work capability during facility outage.", responseType: "ternary", evidenceRequired: "Remote work policy and VPN/cloud access verification.", relatedService: "Business Continuity Planning", relatedPlaybook: "Business Continuity" }),
  meta({ code: "Q43", v2QuestionId: "BCP-012", v2Category: "business_continuity", capability: "Emergency Communications", purpose: "Evaluate emergency contact procedures.", responseType: "ternary", evidenceRequired: "Emergency contact list and communication plan.", relatedService: "Business Continuity Planning", relatedPlaybook: "Business Continuity" }),
  meta({ code: "Q44", v2QuestionId: "BCP-013", v2Category: "business_continuity", capability: "Environmental Protection", purpose: "Evaluate protection from environmental hazards.", responseType: "ternary", evidenceRequired: "Facility assessment or equipment placement review.", relatedService: "Infrastructure Services", relatedPlaybook: "Business Continuity" }),
  meta({ code: "Q45", v2QuestionId: "BCP-014", v2Category: "business_continuity", capability: "Generator Power", purpose: "Evaluate generator availability for critical systems.", responseType: "ternary", evidenceRequired: "Generator maintenance records or facility documentation.", relatedService: "Infrastructure Services", relatedPlaybook: "Business Continuity" }),
  meta({ code: "Q46", v2QuestionId: "SIT-001", v2Category: "strategic_it", capability: "Technology Roadmap", purpose: "Evaluate documented technology roadmap.", responseType: "ternary", evidenceRequired: "Technology roadmap document or project plan.", relatedService: "Technology Strategy", relatedPlaybook: "Strategic IT Planning" }),
  meta({ code: "Q47", v2QuestionId: "SIT-002", v2Category: "strategic_it", capability: "Technology Budgeting", purpose: "Evaluate annual technology spending budget.", responseType: "ternary", evidenceRequired: "Budget allocation documentation.", relatedService: "Technology Strategy", relatedPlaybook: "Strategic IT Planning" }),
  meta({ code: "Q48", v2QuestionId: "SIT-003", v2Category: "strategic_it", capability: "Leadership Engagement", purpose: "Evaluate technology risk review with leadership.", responseType: "ternary", evidenceRequired: "Meeting minutes or QBR records.", relatedService: "Technology Strategy", relatedPlaybook: "Strategic IT Planning" }),
  meta({ code: "Q49", v2QuestionId: "SIT-004", v2Category: "strategic_it", capability: "Hardware Refresh Planning", purpose: "Evaluate proactive hardware refresh planning.", responseType: "ternary", evidenceRequired: "Refresh schedule or capital plan.", relatedService: "Technology Lifecycle Management", relatedPlaybook: "Strategic IT Planning" }),
  meta({ code: "Q50", v2QuestionId: "SIT-005", v2Category: "strategic_it", capability: "Technology Reporting", purpose: "Evaluate regular technology status reporting to leadership.", responseType: "ternary", evidenceRequired: "Sample status report or reporting cadence documentation.", relatedService: "Technology Strategy", relatedPlaybook: "Strategic IT Planning" }),
];

export const QUESTION_METADATA_BY_CODE = new Map(
  QUESTION_LIBRARY_METADATA.map((entry) => [entry.code, entry]),
);

export const V2_CATEGORY_METADATA: Record<string, { v2CategoryCode: string; v2DisplayName: string }> = {
  security: { v2CategoryCode: "security", v2DisplayName: "Security" },
  backup: { v2CategoryCode: "business_continuity", v2DisplayName: "Business Continuity" },
  infrastructure: { v2CategoryCode: "infrastructure", v2DisplayName: "Infrastructure" },
  endpoint: { v2CategoryCode: "operations", v2DisplayName: "Operations" },
  documentation: { v2CategoryCode: "documentation", v2DisplayName: "Documentation" },
  bcdr: { v2CategoryCode: "business_continuity", v2DisplayName: "Business Continuity" },
  strategic: { v2CategoryCode: "strategic_it", v2DisplayName: "Strategic IT" },
};
