import { StyleSheet } from "@react-pdf/renderer";
import { PDF_COLORS as COLORS } from "@/lib/pdf/shared/colors";

export const pdfComponentStyles = StyleSheet.create({
  footer: {
    position: "absolute",
    bottom: 28,
    left: 54,
    right: 54,
    borderTopWidth: 1,
    borderTopColor: COLORS.border,
    paddingTop: 10,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    fontSize: 8,
    color: COLORS.muted,
  },
  footerCenter: { fontSize: 8, color: COLORS.muted, textAlign: "center" },
  confidentialFooter: {
    position: "absolute",
    bottom: 24,
    left: 54,
    right: 54,
    borderTopWidth: 1,
    borderTopColor: COLORS.border,
    paddingTop: 10,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 12,
  },
  confidentialFooterLeft: {
    fontSize: 7,
    color: COLORS.muted,
    lineHeight: 1.5,
    maxWidth: "42%",
  },
  confidentialFooterCenter: {
    fontSize: 7,
    color: COLORS.muted,
    textAlign: "center",
    flex: 1,
  },
  confidentialFooterPage: {
    fontSize: 7,
    color: COLORS.muted,
    textAlign: "right",
    minWidth: 72,
  },
  sectionTitleWrap: { marginBottom: 14, marginTop: 4 },
  sectionTitle: {
    fontSize: 14,
    fontFamily: "Helvetica-Bold",
    color: COLORS.navy,
    paddingBottom: 6,
    borderBottomWidth: 2,
    borderBottomColor: COLORS.navy,
  },
  sectionSubtitle: {
    fontSize: 9,
    color: COLORS.muted,
    marginTop: 6,
    lineHeight: 1.5,
  },
  gaugeCard: {
    flex: 1,
    backgroundColor: COLORS.white,
    borderRadius: 6,
    padding: 14,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  gaugeCardAccent: {
    flex: 1,
    backgroundColor: COLORS.navyLight,
    borderRadius: 6,
    padding: 14,
    borderWidth: 1,
    borderColor: COLORS.navy,
  },
  gaugeLabel: {
    fontSize: 8,
    color: COLORS.muted,
    textTransform: "uppercase",
    letterSpacing: 0.6,
    marginBottom: 6,
  },
  gaugeValue: {
    fontSize: 28,
    fontFamily: "Helvetica-Bold",
    color: COLORS.navy,
    lineHeight: 1,
    marginBottom: 4,
  },
  gaugeRating: {
    fontSize: 9,
    fontFamily: "Helvetica-Bold",
    color: COLORS.navy,
    marginBottom: 10,
  },
  gaugeTrack: {
    height: 10,
    backgroundColor: "#E2E8F0",
    borderRadius: 5,
    position: "relative",
    overflow: "hidden",
  },
  gaugeFill: { height: 10, borderRadius: 5 },
  targetLine: {
    position: "absolute",
    top: 0,
    bottom: 0,
    width: 2,
    backgroundColor: COLORS.target,
    opacity: 0.65,
  },
  targetCaption: {
    fontSize: 7,
    color: COLORS.muted,
    marginTop: 4,
    textAlign: "right",
  },
  priorityBadge: {
    paddingVertical: 4,
    paddingHorizontal: 8,
    borderRadius: 4,
    borderWidth: 1,
    fontSize: 7,
    fontFamily: "Helvetica-Bold",
    letterSpacing: 0.5,
  },
  bulletSection: { marginBottom: 14 },
  bulletHeading: {
    fontSize: 10,
    fontFamily: "Helvetica-Bold",
    color: COLORS.navy,
    marginBottom: 6,
  },
  bulletItem: {
    fontSize: 9,
    lineHeight: 1.55,
    color: COLORS.slate,
    marginBottom: 4,
    paddingLeft: 10,
  },
  pageHeader: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: 64,
    backgroundColor: COLORS.white,
    borderBottomWidth: 2,
    borderBottomColor: COLORS.navy,
    paddingHorizontal: 54,
    paddingTop: 18,
    paddingBottom: 12,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  pageHeaderLeft: { flexDirection: "row", alignItems: "center", gap: 10 },
  pageHeaderLogo: { width: 28, height: 28, objectFit: "contain" },
  pageHeaderBrand: {
    fontSize: 8,
    fontFamily: "Helvetica-Bold",
    color: COLORS.navy,
    letterSpacing: 0.4,
  },
  pageHeaderDoc: { fontSize: 7, color: COLORS.muted, marginTop: 2 },
  pageHeaderRight: { alignItems: "flex-end" },
  pageHeaderClient: {
    fontSize: 9,
    fontFamily: "Helvetica-Bold",
    color: COLORS.slate,
    marginBottom: 2,
  },
  pageHeaderDate: { fontSize: 7, color: COLORS.muted },
  closingHero: {
    backgroundColor: COLORS.navy,
    borderRadius: 8,
    padding: 20,
    marginBottom: 18,
  },
  closingHeroTitle: {
    fontSize: 18,
    fontFamily: "Helvetica-Bold",
    color: COLORS.white,
    marginBottom: 6,
  },
  closingHeroSubtitle: {
    fontSize: 10,
    color: "rgba(255,255,255,0.85)",
    lineHeight: 1.5,
  },
  journeySteps: { flexDirection: "row", justifyContent: "space-between", marginTop: 14 },
  journeyStep: { alignItems: "center", width: "30%" },
  journeyStepDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: COLORS.accent,
    marginBottom: 6,
  },
  journeyStepDotActive: { backgroundColor: COLORS.white },
  journeyStepLabel: { fontSize: 8, color: "rgba(255,255,255,0.9)", textAlign: "center" },
});
