import { StyleSheet } from "@react-pdf/renderer";
import { PDF_COLORS as COLORS } from "@/lib/pdf/shared/colors";
import { REPORT_RADIUS, REPORT_SPACING, REPORT_TYPOGRAPHY } from "@/lib/pdf/shared/tokens";

export const pdfComponentStyles = StyleSheet.create({
  footer: {
    position: "absolute",
    bottom: 24,
    left: REPORT_SPACING.pagePaddingX,
    right: REPORT_SPACING.pagePaddingX,
    borderTopWidth: 1,
    borderTopColor: COLORS.border,
    paddingTop: 10,
    flexDirection: "column",
    gap: 4,
  },
  footerRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 12,
  },
  footerLeft: {
    fontSize: REPORT_TYPOGRAPHY.footer,
    color: COLORS.muted,
    lineHeight: 1.45,
    maxWidth: "34%",
  },
  footerCenter: {
    fontSize: REPORT_TYPOGRAPHY.footer,
    color: COLORS.muted,
    textAlign: "center",
    flex: 1,
    lineHeight: 1.45,
  },
  footerRight: {
    fontSize: REPORT_TYPOGRAPHY.footer,
    color: COLORS.muted,
    textAlign: "right",
    minWidth: 72,
  },
  footerConfidential: {
    fontSize: 6.5,
    color: COLORS.muted,
    lineHeight: 1.45,
    textAlign: "center",
  },
  confidentialFooter: {
    position: "absolute",
    bottom: 24,
    left: REPORT_SPACING.pagePaddingX,
    right: REPORT_SPACING.pagePaddingX,
    borderTopWidth: 1,
    borderTopColor: COLORS.border,
    paddingTop: 10,
    flexDirection: "column",
    gap: 4,
  },
  sectionTitleWrap: { marginBottom: REPORT_SPACING.block, marginTop: 2 },
  sectionTitle: {
    fontSize: REPORT_TYPOGRAPHY.sectionTitle,
    fontFamily: "Helvetica-Bold",
    color: COLORS.navy,
    paddingBottom: 6,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  sectionAccent: {
    width: 32,
    height: 2,
    backgroundColor: COLORS.accent,
    marginBottom: 6,
  },
  sectionSubtitle: {
    fontSize: REPORT_TYPOGRAPHY.sectionSubtitle,
    color: COLORS.muted,
    marginTop: 6,
    lineHeight: 1.55,
  },
  kpiCard: {
    flex: 1,
    backgroundColor: COLORS.white,
    borderRadius: REPORT_RADIUS.md,
    padding: REPORT_SPACING.cardPadding,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  kpiCardHighlight: {
    flex: 1,
    backgroundColor: COLORS.surface,
    borderRadius: REPORT_RADIUS.md,
    padding: REPORT_SPACING.cardPadding,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  kpiLabel: {
    fontSize: REPORT_TYPOGRAPHY.kpiLabel,
    color: COLORS.muted,
    textTransform: "uppercase",
    letterSpacing: 0.6,
    marginBottom: 6,
  },
  kpiValue: {
    fontSize: REPORT_TYPOGRAPHY.kpiValue,
    fontFamily: "Helvetica-Bold",
    color: COLORS.navy,
    lineHeight: 1,
    marginBottom: 4,
  },
  kpiCaption: {
    fontSize: REPORT_TYPOGRAPHY.bodySmall,
    color: COLORS.muted,
    lineHeight: 1.4,
  },
  gaugeCard: {
    flex: 1,
    backgroundColor: COLORS.white,
    borderRadius: REPORT_RADIUS.md,
    padding: REPORT_SPACING.cardPadding,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  gaugeCardAccent: {
    flex: 1,
    backgroundColor: COLORS.surface,
    borderRadius: REPORT_RADIUS.md,
    padding: REPORT_SPACING.cardPadding,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  gaugeLabel: {
    fontSize: REPORT_TYPOGRAPHY.kpiLabel,
    color: COLORS.muted,
    textTransform: "uppercase",
    letterSpacing: 0.6,
    marginBottom: 6,
  },
  gaugeValue: {
    fontSize: REPORT_TYPOGRAPHY.kpiValue,
    fontFamily: "Helvetica-Bold",
    color: COLORS.navy,
    lineHeight: 1,
    marginBottom: 4,
  },
  gaugeRating: {
    fontSize: REPORT_TYPOGRAPHY.bodySmall,
    fontFamily: "Helvetica-Bold",
    color: COLORS.accent,
    marginBottom: 10,
  },
  gaugeTrack: {
    height: 8,
    backgroundColor: COLORS.border,
    borderRadius: REPORT_RADIUS.sm,
    position: "relative",
    overflow: "hidden",
  },
  gaugeFill: { height: 8, borderRadius: REPORT_RADIUS.sm },
  targetLine: {
    position: "absolute",
    top: 0,
    bottom: 0,
    width: 1,
    backgroundColor: COLORS.navy,
    opacity: 0.35,
  },
  targetCaption: {
    fontSize: 7,
    color: COLORS.muted,
    marginTop: 4,
    textAlign: "right",
  },
  calloutBox: {
    backgroundColor: COLORS.surface,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderLeftWidth: 3,
    borderLeftColor: COLORS.accent,
    borderRadius: REPORT_RADIUS.md,
    padding: REPORT_SPACING.cardPadding,
    marginBottom: REPORT_SPACING.block,
  },
  calloutTitle: {
    fontSize: REPORT_TYPOGRAPHY.bodySmall,
    fontFamily: "Helvetica-Bold",
    color: COLORS.navy,
    marginBottom: 6,
  },
  calloutBody: {
    fontSize: REPORT_TYPOGRAPHY.bodySmall,
    lineHeight: 1.6,
    color: COLORS.slate,
  },
  calloutWarning: {
    backgroundColor: COLORS.criticalBg,
    borderWidth: 1,
    borderColor: COLORS.criticalBorder,
    borderLeftWidth: 3,
    borderLeftColor: COLORS.critical,
    borderRadius: REPORT_RADIUS.md,
    padding: REPORT_SPACING.cardPadding,
    marginBottom: REPORT_SPACING.block,
  },
  calloutWarningTitle: {
    fontSize: REPORT_TYPOGRAPHY.bodySmall,
    fontFamily: "Helvetica-Bold",
    color: COLORS.critical,
    marginBottom: 4,
  },
  table: {
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: REPORT_RADIUS.md,
    overflow: "hidden",
    marginBottom: REPORT_SPACING.block,
  },
  tableHeader: {
    flexDirection: "row",
    backgroundColor: COLORS.surface,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
    paddingVertical: 8,
    paddingHorizontal: 10,
  },
  tableHeaderCell: {
    fontSize: REPORT_TYPOGRAPHY.tableHeader,
    fontFamily: "Helvetica-Bold",
    color: COLORS.muted,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  tableRow: {
    flexDirection: "row",
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
    backgroundColor: COLORS.white,
  },
  tableRowAlt: {
    backgroundColor: COLORS.surface,
  },
  tableCell: {
    fontSize: REPORT_TYPOGRAPHY.bodySmall,
    color: COLORS.slate,
    lineHeight: 1.45,
  },
  timelineRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginBottom: REPORT_SPACING.element,
  },
  timelineConnector: {
    width: 1,
    backgroundColor: COLORS.border,
    marginHorizontal: 10,
    minHeight: 24,
  },
  timelineDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: COLORS.neutral,
    marginTop: 3,
  },
  timelineDotActive: {
    backgroundColor: COLORS.accent,
  },
  timelineContent: { flex: 1 },
  timelineLabel: {
    fontSize: REPORT_TYPOGRAPHY.bodySmall,
    fontFamily: "Helvetica-Bold",
    color: COLORS.navy,
    marginBottom: 2,
  },
  timelineMeta: {
    fontSize: 7,
    color: COLORS.muted,
    lineHeight: 1.45,
  },
  emptyState: {
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: REPORT_RADIUS.md,
    backgroundColor: COLORS.surface,
    padding: 20,
    alignItems: "center",
  },
  emptyStateTitle: {
    fontSize: REPORT_TYPOGRAPHY.bodySmall,
    fontFamily: "Helvetica-Bold",
    color: COLORS.navy,
    marginBottom: 4,
  },
  emptyStateText: {
    fontSize: REPORT_TYPOGRAPHY.bodySmall,
    color: COLORS.muted,
    textAlign: "center",
    lineHeight: 1.5,
  },
  priorityBadge: {
    paddingVertical: 3,
    paddingHorizontal: 7,
    borderRadius: REPORT_RADIUS.sm,
    borderWidth: 1,
    fontSize: 7,
    fontFamily: "Helvetica-Bold",
    letterSpacing: 0.5,
  },
  bulletSection: { marginBottom: REPORT_SPACING.block },
  bulletHeading: {
    fontSize: REPORT_TYPOGRAPHY.bodySmall,
    fontFamily: "Helvetica-Bold",
    color: COLORS.navy,
    marginBottom: 6,
  },
  bulletItem: {
    fontSize: REPORT_TYPOGRAPHY.bodySmall,
    lineHeight: 1.55,
    color: COLORS.slate,
    marginBottom: 4,
    paddingLeft: 10,
  },
  pageHeader: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: 56,
    backgroundColor: COLORS.white,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
    paddingHorizontal: REPORT_SPACING.pagePaddingX,
    paddingTop: 16,
    paddingBottom: 10,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  pageHeaderLeft: { flexDirection: "row", alignItems: "center", gap: 10 },
  pageHeaderLogo: { width: 24, height: 24, objectFit: "contain" },
  pageHeaderBrand: {
    fontSize: 8,
    fontFamily: "Helvetica-Bold",
    color: COLORS.navy,
    letterSpacing: 0.3,
  },
  pageHeaderDoc: { fontSize: 7, color: COLORS.muted, marginTop: 2 },
  pageHeaderRight: { alignItems: "flex-end" },
  pageHeaderClient: {
    fontSize: 10,
    fontFamily: "Helvetica-Bold",
    color: COLORS.slate,
    marginBottom: 2,
  },
  pageHeaderScore: {
    fontSize: 9,
    fontFamily: "Helvetica-Bold",
    color: COLORS.navy,
    marginBottom: 2,
  },
  pageHeaderDate: { fontSize: 8, color: COLORS.muted, lineHeight: 1.4 },
  coverPage: {
    paddingTop: 0,
    paddingBottom: REPORT_SPACING.pagePaddingBottom,
    paddingHorizontal: 0,
    fontFamily: "Helvetica",
    fontSize: REPORT_TYPOGRAPHY.body,
    color: COLORS.slate,
    backgroundColor: COLORS.white,
  },
  coverAccentBar: {
    height: 3,
    backgroundColor: COLORS.accent,
  },
  coverBody: {
    paddingHorizontal: REPORT_SPACING.pagePaddingX,
    paddingTop: 40,
    flexGrow: 1,
  },
  coverEyebrow: {
    fontSize: 8,
    color: COLORS.muted,
    textTransform: "uppercase",
    letterSpacing: 1.2,
    marginBottom: 10,
  },
  coverTitle: {
    fontSize: REPORT_TYPOGRAPHY.coverTitle,
    fontFamily: "Helvetica-Bold",
    color: COLORS.navy,
    lineHeight: 1.2,
    marginBottom: 8,
  },
  coverSubtitle: {
    fontSize: 11,
    color: COLORS.muted,
    lineHeight: 1.55,
    maxWidth: 440,
    marginBottom: 28,
  },
  coverClientName: {
    fontSize: REPORT_TYPOGRAPHY.coverClient,
    fontFamily: "Helvetica-Bold",
    color: COLORS.navy,
    marginBottom: 24,
    lineHeight: 1.25,
  },
  coverMetaGrid: { flexDirection: "row", flexWrap: "wrap", gap: 20, marginBottom: 24 },
  coverMetaBlock: {
    minWidth: 130,
    backgroundColor: COLORS.surface,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: REPORT_RADIUS.md,
    padding: 12,
  },
  coverMetaLabel: {
    fontSize: 7,
    color: COLORS.muted,
    textTransform: "uppercase",
    letterSpacing: 0.8,
    marginBottom: 4,
  },
  coverMetaValue: {
    fontSize: 10,
    fontFamily: "Helvetica-Bold",
    color: COLORS.slate,
    lineHeight: 1.4,
  },
  coverBrandRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    marginTop: 28,
    paddingTop: 20,
    borderTopWidth: 1,
    borderTopColor: COLORS.border,
  },
  coverBrandLogo: { width: 44, height: 44, objectFit: "contain" },
  coverPreparedBy: {
    fontSize: 10,
    fontFamily: "Helvetica-Bold",
    color: COLORS.navy,
    marginBottom: 2,
  },
  coverFinePrint: { fontSize: 8, color: COLORS.muted, lineHeight: 1.5 },
  closingHero: {
    backgroundColor: COLORS.surface,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderLeftWidth: 3,
    borderLeftColor: COLORS.accent,
    borderRadius: REPORT_RADIUS.lg,
    padding: 18,
    marginBottom: REPORT_SPACING.block,
  },
  closingHeroTitle: {
    fontSize: 16,
    fontFamily: "Helvetica-Bold",
    color: COLORS.navy,
    marginBottom: 6,
  },
  closingHeroSubtitle: {
    fontSize: REPORT_TYPOGRAPHY.body,
    color: COLORS.muted,
    lineHeight: 1.55,
  },
  journeySteps: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 14,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: COLORS.border,
  },
  journeyStep: { alignItems: "center", width: "30%" },
  journeyStepDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: COLORS.neutral,
    marginBottom: 6,
  },
  journeyStepDotActive: { backgroundColor: COLORS.accent },
  journeyStepLabel: {
    fontSize: 8,
    color: COLORS.muted,
    textAlign: "center",
  },
});
