"use client";

import { BRAND } from "@/lib/branding";
import { getPriorityTimeline } from "@/lib/recommendations/display";
import { buildTipReportData } from "@/lib/technology-improvement-plan/report-data";
import { formatCurrency } from "@/lib/technology-improvement-plan/pricing";
import type { TipPlanDetail } from "@/lib/technology-improvement-plan/types";
import { getRating, RATING_LABELS } from "@/lib/scoring";
import { getScoreTextColorClass } from "@/lib/scoring/score-display";
import { cn } from "@/lib/utils";
import type { Priority } from "@/generated/prisma/client";

const PRIORITY_BADGE: Record<Priority, string> = {
  critical: "bg-red-50 text-red-700 border-red-200",
  high: "bg-orange-50 text-orange-800 border-orange-200",
  medium: "bg-slate-50 text-slate-700 border-slate-200",
  low: "bg-white text-slate-500 border-slate-200",
};

type TipReportPreviewProps = {
  plan: TipPlanDetail;
  isAdmin: boolean;
  executiveSummary: string;
  onExecutiveSummaryChange?: (value: string) => void;
  isEditable?: boolean;
};

export function TipReportPreview({
  plan,
  isAdmin,
  executiveSummary,
  onExecutiveSummaryChange,
  isEditable = false,
}: TipReportPreviewProps) {
  const data = buildTipReportData(
    {
      ...plan,
      executiveSummary,
      wizardState: { ...plan.wizardState, executiveSummary },
    },
    isAdmin,
  );

  const currentRating = getRating(data.currentScore);
  const projectedRating = getRating(data.projectedScore);

  return (
    <div className="overflow-hidden rounded-xl border bg-white shadow-sm">
      {/* Cover */}
      <div className="bg-primary px-8 py-10 text-primary-foreground">
        <p className="text-xs uppercase tracking-[0.2em] text-primary-foreground/70">
          Generated by {BRAND.productName}
        </p>
        <h3 className="mt-2 text-3xl font-bold tracking-tight">Technology Improvement Plan</h3>
        <p className="mt-3 max-w-2xl text-sm leading-relaxed text-primary-foreground/85">
          A strategic roadmap to strengthen technology resilience, reduce risk, and deliver
          measurable business outcomes
        </p>
      </div>

      <div className="space-y-8 px-8 py-8">
        <div className="border-b pb-6">
          <p className="text-xs font-semibold uppercase tracking-wide text-primary">
            Prepared by {BRAND.companyName}
          </p>
          <p className="mt-4 text-2xl font-bold text-primary">{data.clientName}</p>
          <div className="mt-4 flex flex-wrap gap-6 text-sm">
            <div>
              <p className="text-xs uppercase tracking-wide text-muted-foreground">Version</p>
              <p className="font-semibold">v{data.version}</p>
            </div>
            <div>
              <p className="text-xs uppercase tracking-wide text-muted-foreground">Prepared</p>
              <p className="font-semibold">{data.generatedDate}</p>
            </div>
            {data.maturityTierLabel ? (
              <div>
                <p className="text-xs uppercase tracking-wide text-muted-foreground">Maturity</p>
                <p className="font-semibold">{data.maturityTierLabel}</p>
              </div>
            ) : null}
          </div>
          <p className="mt-6 text-xs leading-relaxed text-muted-foreground">
            CONFIDENTIAL — Prepared exclusively for {data.clientName} by {BRAND.companyName}.
          </p>
        </div>

        {/* Report header strip */}
        <div className="flex items-center justify-between border-b-2 border-primary pb-3">
          <div>
            <p className="text-xs font-bold text-primary">
              {BRAND.companyName} · {BRAND.productName}
            </p>
            <p className="text-xs text-muted-foreground">Technology Improvement Plan</p>
          </div>
          <div className="text-right text-xs">
            <p className="font-semibold">{data.clientName}</p>
            <p className="text-muted-foreground">{data.generatedDate}</p>
          </div>
        </div>

        {/* Executive summary */}
        <PreviewSection
          title="Executive Summary"
          subtitle="Business context, profile trajectory, and expected outcomes"
        >
          {isEditable && onExecutiveSummaryChange ? (
            <textarea
              className="min-h-28 w-full rounded-lg border bg-background px-3 py-2 text-sm leading-relaxed"
              value={executiveSummary}
              onChange={(event) => onExecutiveSummaryChange(event.target.value)}
              placeholder="Summarize current state, priorities, and expected business outcomes."
            />
          ) : (
            <p className="text-sm leading-relaxed text-foreground/90">
              {executiveSummary ||
                `This plan outlines prioritized initiatives to advance ${data.clientName}'s technology posture from ${data.currentScore} to a projected ${data.projectedScore}.`}
            </p>
          )}
          <div className="mt-4 grid gap-4 sm:grid-cols-2">
            <ScoreCard
              label="Technology Profile — Today"
              score={data.currentScore}
              rating={RATING_LABELS[currentRating]}
            />
            <ScoreCard
              label="Technology Profile — Projected"
              score={data.projectedScore}
              rating={RATING_LABELS[projectedRating]}
              accent
            />
          </div>
          <div className="mt-4 rounded-lg border bg-primary/5 p-4">
            <p className="text-xs font-semibold uppercase tracking-wide text-primary">
              Technology Journey — {data.journeyPhaseLabel}
            </p>
            <div className="mt-3 h-3 overflow-hidden rounded-full border bg-background">
              <div
                className="h-full rounded-full bg-primary transition-all"
                style={{ width: `${data.journeyProgressPercent}%` }}
              />
            </div>
            <p className="mt-2 text-xs text-muted-foreground">
              {data.journeyProgressPercent}% complete · +{data.scoreImprovement} projected points
            </p>
          </div>
        </PreviewSection>

        {/* Business outcomes */}
        {data.businessOutcomes.length > 0 ? (
          <PreviewSection
            title="Expected Business Outcomes"
            subtitle="Primary value drivers from prioritized initiatives"
          >
            <div className="grid gap-3 sm:grid-cols-2">
              {data.businessOutcomes.map((outcome) => (
                <div
                  key={outcome.title}
                  className="rounded-lg border border-l-4 border-l-primary bg-background p-4"
                >
                  <p className="text-sm font-semibold text-primary">{outcome.title}</p>
                  <p className="mt-2 text-xs leading-relaxed text-muted-foreground">
                    {outcome.description}
                  </p>
                </div>
              ))}
            </div>
          </PreviewSection>
        ) : null}

        {/* Categories */}
        {data.categorySummaries.length > 0 ? (
          <PreviewSection
            title="Category Profile Summary"
            subtitle="Highlighted categories include planned improvements"
          >
            <div className="space-y-3">
              {data.categorySummaries.map((category) => (
                <div
                  key={category.name}
                  className={cn(
                    "rounded-lg border p-3",
                    category.hasRecommendations && "border-primary bg-primary/5",
                  )}
                >
                  <div className="flex items-center justify-between gap-2">
                    <p className="text-sm font-semibold text-primary">{category.name}</p>
                    <p className={cn("text-sm font-bold", getScoreTextColorClass(category.score))}>
                      {category.score}%
                    </p>
                  </div>
                  <p className="mt-1 text-xs text-muted-foreground">
                    {category.ratingLabel}
                    {category.hasRecommendations ? " · Improvement planned" : ""}
                  </p>
                </div>
              ))}
            </div>
          </PreviewSection>
        ) : null}

        {/* Recommendations */}
        <PreviewSection
          title="Prioritized Recommendations"
          subtitle="Initiatives ordered by business impact and priority"
        >
          <div className="space-y-4">
            {data.recommendations.map((rec) => (
              <div
                key={rec.id}
                className="overflow-hidden rounded-lg border border-t-4 border-t-primary bg-background"
              >
                <div className="flex items-start justify-between gap-3 p-4 pb-2">
                  <p className="font-semibold text-primary">{rec.title}</p>
                  <span
                    className={cn(
                      "shrink-0 rounded border px-2 py-0.5 text-[10px] font-bold uppercase tracking-wide",
                      PRIORITY_BADGE[rec.priority],
                    )}
                  >
                    {rec.priority}
                  </span>
                </div>
                <div className="grid gap-2 px-4 pb-4 sm:grid-cols-3">
                  <MetaBox label="Expected Outcome" value={`+${rec.estimatedImpactPoints} pts`} />
                  <MetaBox label="Timeline" value={getPriorityTimeline(rec.priority)} />
                  <MetaBox label="Category" value={rec.categoryName} />
                </div>
                <div className="border-t bg-muted/30 px-4 py-3">
                  <p className="text-[10px] font-semibold uppercase tracking-wide text-muted-foreground">
                    Business Impact
                  </p>
                  <p className="mt-1 text-sm leading-relaxed">{rec.businessImpact}</p>
                </div>
              </div>
            ))}
          </div>
        </PreviewSection>

        {/* Roadmap */}
        <PreviewSection title="Phased Implementation Roadmap">
          <div className="space-y-3">
            {data.roadmapPhases.map((phase, index) => (
              <div
                key={phase.id}
                className={cn(
                  "rounded-lg border p-4",
                  index === 0 && "border-primary bg-primary/5",
                )}
              >
                <div className="flex items-center justify-between gap-2">
                  <p className="font-semibold text-primary">{phase.label}</p>
                  <p className={cn("text-lg font-bold", getScoreTextColorClass(phase.projectedScore))}>
                    {phase.projectedScore}
                  </p>
                </div>
                <p className="mt-1 text-xs text-muted-foreground">+{phase.scoreDelta} points</p>
                <ul className="mt-2 space-y-1 text-sm text-muted-foreground">
                  {phase.recommendations.map((rec) => (
                    <li key={rec.id}>• {rec.title}</li>
                  ))}
                </ul>
              </div>
            ))}
          </div>
        </PreviewSection>

        {/* Investment */}
        <PreviewSection
          title="Investment Summary"
          subtitle="Client-facing investment breakdown"
        >
          <div className="overflow-hidden rounded-lg border">
            <div className="grid grid-cols-[1fr_2fr_auto] gap-3 bg-primary px-4 py-2 text-[10px] font-bold uppercase tracking-wide text-primary-foreground">
              <span>Category</span>
              <span>Description</span>
              <span className="text-right">Amount</span>
            </div>
            {data.investmentLineItems.map((row, index) => (
              <div
                key={row.category}
                className={cn(
                  "grid grid-cols-[1fr_2fr_auto] gap-3 border-t px-4 py-3 text-sm",
                  index % 2 === 1 && "bg-muted/20",
                )}
              >
                <span className="font-semibold text-primary">{row.category}</span>
                <span className="text-xs leading-relaxed text-muted-foreground">{row.description}</span>
                <span className="text-right font-semibold">{formatCurrency(row.amount)}</span>
              </div>
            ))}
          </div>
          <div className="mt-4 rounded-lg bg-primary px-6 py-5 text-primary-foreground">
            <p className="text-xs uppercase tracking-wide text-primary-foreground/75">
              Total Client Investment
            </p>
            <p className="mt-1 text-3xl font-bold">{formatCurrency(data.clientInvestmentTotal)}</p>
          </div>
          {isAdmin && data.investmentBreakdown ? (
            <div className="mt-4 rounded-lg border border-dashed border-amber-300 bg-amber-50/50 p-4">
              <p className="text-xs font-semibold uppercase tracking-wide text-amber-800">
                Internal Pricing (Admin Only — not in client PDF)
              </p>
              <div className="mt-2 grid gap-2 text-sm sm:grid-cols-2">
                <p>Margin: {data.investmentBreakdown.marginPercent}%</p>
                <p>Margin amount: {formatCurrency(data.investmentBreakdown.marginAmount)}</p>
                <p>Labor: {formatCurrency(data.investmentBreakdown.labor)}</p>
                <p>Hardware: {formatCurrency(data.investmentBreakdown.hardware)}</p>
              </div>
            </div>
          ) : null}
        </PreviewSection>

        {/* Footer preview */}
        <div className="border-t pt-4 text-center text-[10px] leading-relaxed text-muted-foreground">
          Confidential — Prepared for {data.clientName} by {BRAND.companyName} · Generated by{" "}
          {BRAND.productName}
        </div>
      </div>
    </div>
  );
}

function PreviewSection({
  title,
  subtitle,
  children,
}: {
  title: string;
  subtitle?: string;
  children: React.ReactNode;
}) {
  return (
    <section>
      <div className="mb-4 border-b-2 border-primary pb-2">
        <h4 className="text-sm font-bold text-primary">{title}</h4>
        {subtitle ? <p className="mt-1 text-xs text-muted-foreground">{subtitle}</p> : null}
      </div>
      {children}
    </section>
  );
}

function ScoreCard({
  label,
  score,
  rating,
  accent = false,
}: {
  label: string;
  score: number;
  rating: string;
  accent?: boolean;
}) {
  return (
    <div
      className={cn(
        "rounded-lg border p-4",
        accent ? "border-primary bg-primary/5" : "bg-background",
      )}
    >
      <p className="text-[10px] font-semibold uppercase tracking-wide text-muted-foreground">
        {label}
      </p>
      <p className={cn("mt-2 text-3xl font-bold", getScoreTextColorClass(score))}>{score}</p>
      <p className="mt-1 text-xs font-semibold text-primary">{rating}</p>
    </div>
  );
}

function MetaBox({ label, value }: { label: string; value: string }) {
  return (
    <div className="rounded-md border bg-muted/20 px-3 py-2">
      <p className="text-[10px] font-semibold uppercase tracking-wide text-muted-foreground">
        {label}
      </p>
      <p className="mt-1 text-xs font-semibold text-primary">{value}</p>
    </div>
  );
}
