"use client";

import { ArrowDown, ArrowRight, Check } from "lucide-react";
import { BRAND } from "@/lib/branding";
import { formatCurrency } from "@/lib/technology-improvement-plan/pricing";
import { getRating, RATING_LABELS } from "@/lib/scoring";
import { getReportScoreBarClass, getReportScoreTextClass } from "@/lib/reports/document-score-display";
import {
  buildApprovalIntro,
  buildPhaseCompletionOutcomes,
  buildPhaseExecutiveNarrative,
  buildPhaseOutcomeBullets,
  buildTipExecutiveFallback,
  findRecommendationForInitiative,
  getPhasePriorityLabel,
  getRoadmapOverviewMetrics,
  isPhaseRecurringCoveredByRetainer,
  ROADMAP_NEXT_STEPS,
  TIP_MATURITY_TARGET,
} from "@/lib/reports/tip-presentation";
import type { TipReportData } from "@/lib/pdf/types";
import type { RoadmapPhaseResult } from "@/lib/technology-improvement-plan/roadmap-engine";
import { ReportExecutiveSummary } from "@/components/reports/report-executive-summary";
import { ReportPageBreak, ReportPrintLeadGroup } from "@/components/reports";
import { ReportSection } from "@/components/reports/report-section";
import { cn } from "@/lib/utils";
import { getReportTypeMeta } from "@/lib/reports/meta";

const DOCUMENT_THEME = true;

type TipReportCoverProps = {
  data: TipReportData;
};

export function TipReportCover({ data }: TipReportCoverProps) {
  const meta = getReportTypeMeta("technology_improvement_plan");

  return (
    <header className="tip-report-cover print:break-after-page">
      <p className="tip-report-cover-eyebrow">Generated by {BRAND.productName}</p>
      <h1 className="tip-report-cover-title">{meta.title}</h1>
      <p className="tip-report-cover-subtitle">{meta.subtitle}</p>

      <div className="tip-report-cover-meta">
        <div>
          <p className="tip-report-cover-meta-label">Prepared for</p>
          <p className="tip-report-cover-meta-value">{data.clientName}</p>
        </div>
        <div>
          <p className="tip-report-cover-meta-label">Document Version</p>
          <p className="tip-report-cover-meta-value">v{data.version}</p>
        </div>
        <div>
          <p className="tip-report-cover-meta-label">Prepared Date</p>
          <p className="tip-report-cover-meta-value">{data.generatedDate}</p>
        </div>
        {data.assessmentName ? (
          <div>
            <p className="tip-report-cover-meta-label">Based On Assessment</p>
            <p className="tip-report-cover-meta-value">{data.assessmentName}</p>
          </div>
        ) : data.maturityTierLabel ? (
          <div>
            <p className="tip-report-cover-meta-label">Current Maturity</p>
            <p className="tip-report-cover-meta-value">{data.maturityTierLabel}</p>
          </div>
        ) : null}
      </div>

      <p className="tip-report-cover-confidential">
        CONFIDENTIAL — This document contains proprietary analysis prepared exclusively for{" "}
        {data.clientName}. It may not be reproduced or distributed without written consent from{" "}
        {BRAND.companyName}.
      </p>
    </header>
  );
}

type TipMaturityHeroProps = {
  currentScore: number;
  projectedScore: number;
  scoreImprovement: number;
  journeyPhaseLabel: string;
  journeyProgressPercent: number;
};

export function TipMaturityHero({
  currentScore,
  projectedScore,
  scoreImprovement,
  journeyPhaseLabel,
  journeyProgressPercent,
}: TipMaturityHeroProps) {
  const currentRating = getRating(currentScore);
  const projectedRating = getRating(projectedScore);

  return (
    <div className="tip-maturity-hero">
      <h3 className="tip-maturity-hero-heading">Technology Maturity — Current vs Projected</h3>

      <div className="tip-maturity-compare">
        <div className="tip-maturity-card">
          <p className="tip-maturity-card-label">Today</p>
          <p className={cn("tip-maturity-card-score", getReportScoreTextClass(currentScore))}>
            {currentScore}
          </p>
          <p className="tip-maturity-card-rating">{RATING_LABELS[currentRating]}</p>
          <div className="tip-maturity-bar-track">
            <div
              className={cn("tip-maturity-bar-fill", getReportScoreBarClass(currentScore))}
              style={{ width: `${Math.min(100, currentScore)}%` }}
            />
          </div>
        </div>

        <div className="tip-maturity-delta" aria-hidden>
          <ArrowRight className="hidden h-5 w-5 text-[color:var(--report-muted)] md:block" />
          <p className="tip-maturity-delta-value">+{scoreImprovement}</p>
          <p className="tip-maturity-delta-label">StackScore points</p>
        </div>

        <div className="tip-maturity-card tip-maturity-card-projected">
          <p className="tip-maturity-card-label">Projected</p>
          <p className={cn("tip-maturity-card-score", getReportScoreTextClass(projectedScore))}>
            {projectedScore}
          </p>
          <p className="tip-maturity-card-rating">{RATING_LABELS[projectedRating]}</p>
          <div className="tip-maturity-bar-track">
            <div
              className={cn("tip-maturity-bar-fill", getReportScoreBarClass(projectedScore))}
              style={{ width: `${Math.min(100, projectedScore)}%` }}
            />
          </div>
        </div>
      </div>

      <div className="tip-journey-strip">
        <p className="tip-journey-strip-title">Technology Journey — {journeyPhaseLabel} Phase</p>
        <div className="tip-journey-strip-track">
          <div
            className="tip-journey-strip-fill"
            style={{ width: `${Math.min(100, journeyProgressPercent)}%` }}
          />
        </div>
        <p className="tip-journey-strip-meta">
          Journey progress: {journeyProgressPercent}% · Available improvement: +{scoreImprovement}{" "}
          points · Maturity target: {TIP_MATURITY_TARGET}+
        </p>
      </div>
    </div>
  );
}

type TipExecutiveSummarySectionProps = {
  data: TipReportData;
  executiveSummary: string;
  isEditable?: boolean;
  onExecutiveSummaryChange?: (value: string) => void;
};

export function TipExecutiveSummarySection({
  data,
  executiveSummary,
  isEditable,
  onExecutiveSummaryChange,
}: TipExecutiveSummarySectionProps) {
  const fallback = buildTipExecutiveFallback(
    data.clientName,
    data.currentScore,
    data.projectedScore,
  );
  const paragraphs = (executiveSummary || fallback).trim().split(/\n\n+/).filter(Boolean);

  return (
    <ReportSection
      title="Executive Summary"
      subtitle="Strategic context for a phased technology roadmap"
      documentTheme={DOCUMENT_THEME}
    >
      <ReportPrintLeadGroup>
        {isEditable && onExecutiveSummaryChange ? (
          <ReportExecutiveSummary
            value={executiveSummary}
            isEditable
            onChange={onExecutiveSummaryChange}
            fallback={fallback}
            className="tip-executive-prose min-h-32 rounded-lg border bg-[color:var(--report-background)] px-3 py-2"
          />
        ) : (
          <div className="tip-executive-prose-stack tip-executive-prose">
            {paragraphs.map((paragraph) => (
              <p key={paragraph.slice(0, 48)}>{paragraph}</p>
            ))}
          </div>
        )}
      </ReportPrintLeadGroup>
    </ReportSection>
  );
}

export function TipCurrentMaturitySection({ data }: { data: TipReportData }) {
  return (
    <ReportSection
      title="Current Technology Maturity"
      subtitle="Where the organization stands today and the improvement trajectory ahead"
      documentTheme={DOCUMENT_THEME}
    >
      <ReportPrintLeadGroup>
        <TipMaturityHero
          currentScore={data.currentScore}
          projectedScore={data.projectedScore}
          scoreImprovement={data.scoreImprovement}
          journeyPhaseLabel={data.journeyPhaseLabel}
          journeyProgressPercent={data.journeyProgressPercent}
        />
      </ReportPrintLeadGroup>

      {data.categorySummaries.length > 0 ? (
        <div className="tip-pillar-grid mt-6">
          {data.categorySummaries.map((category) => (
            <article
              key={category.name}
              className={cn(
                "tip-pillar-scorecard",
                category.hasRecommendations && "tip-pillar-scorecard-planned",
              )}
            >
              <div className="tip-pillar-scorecard-header">
                <p className="tip-pillar-scorecard-name">{category.name}</p>
                <p
                  className={cn(
                    "tip-pillar-scorecard-score",
                    getReportScoreTextClass(category.score),
                  )}
                >
                  {category.score}
                </p>
              </div>
              <p className="tip-pillar-scorecard-rating">{category.ratingLabel}</p>
              <div className="tip-pillar-scorecard-bar-track">
                <div
                  className={cn(
                    "tip-pillar-scorecard-bar-fill",
                    getReportScoreBarClass(category.score),
                  )}
                  style={{ width: `${Math.min(100, category.score)}%` }}
                />
              </div>
              <p className="tip-pillar-scorecard-foot">
                {category.hasRecommendations
                  ? "Improvement initiative planned in this domain"
                  : "Baseline maturity — no active initiatives in this plan"}
              </p>
              {category.hasRecommendations ? (
                <span className="tip-pillar-scorecard-badge">Improvement planned</span>
              ) : null}
            </article>
          ))}
        </div>
      ) : null}
    </ReportSection>
  );
}

export function TipRoadmapOverviewSection({ data }: { data: TipReportData }) {
  const roadmap = data.technologyRoadmap;
  const metrics = getRoadmapOverviewMetrics(
    data.currentScore,
    roadmap,
    data.recommendations,
  );

  return (
    <ReportSection
      title="Living Execution Plan Overview"
      subtitle="A sequenced journey from assessment through strategic enhancement"
      documentTheme={DOCUMENT_THEME}
    >
      <ReportPrintLeadGroup>
        <div className="tip-roadmap-overview-flow">
          <div className="tip-roadmap-overview-node tip-roadmap-overview-node-start">
            <p className="tip-roadmap-overview-node-label">Starting Point</p>
            <p className="tip-roadmap-overview-node-title">Assessment Complete</p>
          </div>

          {roadmap.phases.map((phase) => (
            <div key={phase.id} className="tip-roadmap-overview-step">
              <ArrowDown className="tip-roadmap-overview-arrow" aria-hidden />
              <div className="tip-roadmap-overview-node">
                <p className="tip-roadmap-overview-node-label">{phase.subtitle}</p>
                <p className="tip-roadmap-overview-node-title">{phase.name}</p>
                <p className="tip-roadmap-overview-node-meta">{phase.timeline}</p>
              </div>
            </div>
          ))}
        </div>

        <div className="tip-roadmap-overview-metrics">
          <OverviewMetric label="Current StackScore" value={String(metrics.currentScore)} />
          <OverviewMetric
            label="Projected StackScore"
            value={String(metrics.projectedScore)}
            emphasis
          />
          <OverviewMetric
            label="Available Improvement"
            value={`+${metrics.scoreImprovement}`}
          />
          <OverviewMetric label="Initiatives" value={String(metrics.initiativeCount)} />
          <OverviewMetric label="Implementation Phases" value={String(metrics.phaseCount)} />
        </div>
      </ReportPrintLeadGroup>
    </ReportSection>
  );
}

function OverviewMetric({
  label,
  value,
  emphasis = false,
}: {
  label: string;
  value: string;
  emphasis?: boolean;
}) {
  return (
    <div className={cn("tip-roadmap-overview-metric", emphasis && "tip-roadmap-overview-metric-emphasis")}>
      <p className="tip-roadmap-overview-metric-label">{label}</p>
      <p className="tip-roadmap-overview-metric-value">{value}</p>
    </div>
  );
}

export function TipPhaseDetailSections({ data }: { data: TipReportData }) {
  const phases = data.technologyRoadmap.phases;
  if (phases.length === 0) return null;

  return (
    <ReportSection
      title="Implementation Phases"
      subtitle="Each phase is designed for independent approval and incremental delivery"
      documentTheme={DOCUMENT_THEME}
    >
      <div className="tip-phase-stack">
        {phases.map((phase, index) => {
          const card = <TipPhaseDetailCard data={data} phase={phase} />;
          if (index === 0) {
            return <ReportPrintLeadGroup key={phase.id}>{card}</ReportPrintLeadGroup>;
          }
          return (
            <div key={phase.id} className="contents">
              {card}
            </div>
          );
        })}
      </div>
    </ReportSection>
  );
}

function TipPhaseDetailCard({
  data,
  phase,
}: {
  data: TipReportData;
  phase: RoadmapPhaseResult;
}) {
  const outcomes = buildPhaseOutcomeBullets(phase);
  const completionOutcomes = buildPhaseCompletionOutcomes(phase);
  const coveredByRetainer = isPhaseRecurringCoveredByRetainer(phase, data.recommendations);
  const showMonthly = phase.monthlyRecurringInvestment > 0;

  return (
    <article className="tip-phase-section">
      <header className="tip-phase-header">
        <div>
          <p className="tip-phase-subtitle">{phase.subtitle}</p>
          <h3 className="tip-phase-title">{phase.name}</h3>
        </div>
        <div className="tip-phase-meta-grid">
          <PhaseMeta label="Timeline" value={phase.timeline} />
          <PhaseMeta label="Priority" value={getPhasePriorityLabel(phase)} />
          <PhaseMeta
            label="Expected StackScore Improvement"
            value={`+${phase.stackScoreImprovement} Points`}
            emphasis
          />
        </div>
      </header>

      <div className="tip-phase-block">
        <p className="tip-phase-block-label">Executive Summary</p>
        <p className="tip-executive-prose">{buildPhaseExecutiveNarrative(phase)}</p>
      </div>

      {outcomes.length > 0 ? (
        <div className="tip-phase-block">
          <p className="tip-phase-block-label">Business Outcomes</p>
          <ul className="tip-outcome-checklist">
            {outcomes.map((outcome) => (
              <li key={outcome}>
                <Check className="tip-outcome-check" aria-hidden />
                <span>{outcome}</span>
              </li>
            ))}
          </ul>
        </div>
      ) : null}

      <div className="tip-phase-block">
        <p className="tip-phase-block-label">Included Initiatives</p>
        <div className="tip-phase-initiative-list">
          {phase.initiatives.map((initiative) => {
            const recommendation = findRecommendationForInitiative(
              data.recommendations,
              initiative.recommendationId,
            );
            return (
              <article key={initiative.recommendationId} className="tip-phase-initiative">
                <p className="tip-phase-initiative-title">{initiative.title}</p>
                {recommendation?.description ? (
                  <p className="tip-phase-initiative-desc">{recommendation.description}</p>
                ) : null}
                {recommendation?.businessImpact ? (
                  <p className="tip-phase-initiative-benefit">
                    <span>Business benefit:</span> {recommendation.businessImpact}
                  </p>
                ) : null}
                <p className="tip-phase-initiative-impact">
                  Estimated StackScore contribution: +
                  {recommendation?.estimatedImpactPoints ?? 0} points
                </p>
              </article>
            );
          })}
        </div>
      </div>

      <div className="tip-phase-investment">
        <p className="tip-phase-block-label">Investment Summary</p>
        <div className="tip-phase-investment-grid">
          <div className="tip-phase-investment-card">
            <p className="tip-phase-investment-label">One-Time Implementation Investment</p>
            <p className="tip-phase-investment-value">
              {formatCurrency(phase.oneTimeInvestment)}
            </p>
          </div>
          {showMonthly ? (
            <div className="tip-phase-investment-card">
              <p className="tip-phase-investment-label">New Monthly Recurring Investment</p>
              {coveredByRetainer ? (
                <p className="tip-phase-investment-retainer">
                  Included in Strategic IT Consulting Retainer
                </p>
              ) : (
                <p className="tip-phase-investment-value">
                  {formatCurrency(phase.monthlyRecurringInvestment)}
                  <span className="tip-phase-investment-suffix">/month</span>
                </p>
              )}
            </div>
          ) : null}
        </div>
      </div>

      <div className="tip-phase-completion">
        <p className="tip-phase-block-label">Phase Completion Outcome</p>
        <p className="tip-phase-completion-intro">
          Upon completion of this phase your organization will have:
        </p>
        <ul className="tip-outcome-checklist">
          {completionOutcomes.map((outcome) => (
            <li key={outcome}>
              <Check className="tip-outcome-check" aria-hidden />
              <span>{outcome}</span>
            </li>
          ))}
        </ul>
      </div>
    </article>
  );
}

function PhaseMeta({
  label,
  value,
  emphasis = false,
}: {
  label: string;
  value: string;
  emphasis?: boolean;
}) {
  return (
    <div className={cn("tip-phase-meta", emphasis && "tip-phase-meta-emphasis")}>
      <p className="tip-phase-meta-label">{label}</p>
      <p className="tip-phase-meta-value">{value}</p>
    </div>
  );
}

type TipInvestmentSectionProps = {
  data: TipReportData;
  isAdmin?: boolean;
};

export function TipInvestmentSection({ data, isAdmin = false }: TipInvestmentSectionProps) {
  return (
    <ReportSection
      title="Overall Investment Summary"
      subtitle="One-time implementation and recurring services are presented separately"
      documentTheme={DOCUMENT_THEME}
    >
      <div className="tip-investment-totals">
        <div className="tip-investment-total-card">
          <p className="tip-investment-total-label">Total One-Time Implementation Investment</p>
          <p className="tip-investment-total-value">
            {formatCurrency(data.oneTimeInvestmentTotal)}
          </p>
          <p className="tip-investment-total-caption">
            Project delivery, professional services, and technology required to execute approved
            phases.
          </p>
        </div>

        {data.monthlyRecurringTotal > 0 ? (
          <div className="tip-investment-total-card tip-investment-total-card-secondary">
            <p className="tip-investment-total-label">Total New Monthly Recurring Investment</p>
            <p className="tip-investment-total-value">
              {formatCurrency(data.monthlyRecurringTotal)}
              <span className="tip-phase-investment-suffix">/month</span>
            </p>
            <p className="tip-investment-total-caption">
              Ongoing services introduced by the roadmap. Recurring investment is never combined
              with one-time implementation cost.
            </p>
          </div>
        ) : null}

        {data.annualRecurringTotal > 0 ? (
          <div className="tip-investment-total-card tip-investment-total-card-tertiary">
            <p className="tip-investment-total-label">Total Annual Recurring Investment</p>
            <p className="tip-investment-total-value">
              {formatCurrency(data.annualRecurringTotal)}
              <span className="tip-phase-investment-suffix">/year</span>
            </p>
          </div>
        ) : null}
      </div>

      {data.investmentLineItems.length > 0 ? (
        <div className="tip-investment-table mt-4">
          <div className="tip-investment-table-head">
            <span>Category</span>
            <span>Description</span>
            <span className="text-right">Amount</span>
          </div>
          {data.investmentLineItems.map((row, index) => (
            <div
              key={row.category}
              className={cn(
                "tip-investment-table-row",
                index % 2 === 1 && "tip-investment-table-row-alt",
              )}
            >
              <span className="tip-investment-table-category">{row.category}</span>
              <span className="tip-investment-table-desc">{row.description}</span>
              <span className="tip-investment-table-amount">
                {formatCurrency(row.amount)}
                {row.category.toLowerCase().includes("monthly") ? "/mo" : ""}
              </span>
            </div>
          ))}
        </div>
      ) : null}

      {isAdmin && data.investmentBreakdown ? (
        <div className="mt-4 rounded-lg border border-dashed border-amber-300 bg-amber-50/80 p-4 print:hidden">
          <p className="text-xs font-semibold uppercase tracking-wide text-amber-800">
            Internal Pricing (Admin Only — not in client PDF)
          </p>
          <div className="mt-2 grid gap-2 text-sm text-amber-950 sm:grid-cols-2">
            <p>Margin: {data.investmentBreakdown.marginPercent}%</p>
            <p>Margin amount: {formatCurrency(data.investmentBreakdown.marginAmount)}</p>
            <p>Labor: {formatCurrency(data.investmentBreakdown.labor)}</p>
            <p>Hardware: {formatCurrency(data.investmentBreakdown.hardware)}</p>
            <p>Legacy combined total: {formatCurrency(data.clientInvestmentTotal)}</p>
          </div>
        </div>
      ) : null}
    </ReportSection>
  );
}

export function TipNextStepsSection() {
  return (
    <ReportSection
      title="Next Steps"
      subtitle="Implementation is incremental — approve and deliver one phase at a time"
      documentTheme={DOCUMENT_THEME}
    >
      <div className="tip-next-steps-flow">
        {ROADMAP_NEXT_STEPS.map((step, index) => (
          <div key={step.label} className="tip-next-steps-item">
            <div className="tip-next-steps-node">
              <p className="tip-next-steps-index">{index + 1}</p>
              <div>
                <p className="tip-next-steps-label">{step.label}</p>
                <p className="tip-next-steps-desc">{step.description}</p>
              </div>
            </div>
            {index < ROADMAP_NEXT_STEPS.length - 1 ? (
              <ArrowDown className="tip-next-steps-arrow" aria-hidden />
            ) : null}
          </div>
        ))}
      </div>
    </ReportSection>
  );
}

export function TipApprovalSection({
  clientName,
  phases,
}: {
  clientName: string;
  phases: RoadmapPhaseResult[];
}) {
  return (
    <ReportSection
      title="Approval"
      subtitle="Phases may be approved independently as priorities and budget allow"
      documentTheme={DOCUMENT_THEME}
    >
      <div className="tip-approval-block">
        <p className="tip-executive-prose">{buildApprovalIntro(clientName)}</p>

        <div className="tip-approval-phase-list" data-approval-phases>
          {phases.map((phase) => (
            <div key={phase.id} className="tip-approval-phase-row" data-phase-id={phase.id}>
              <div className="tip-approval-checkbox" aria-hidden />
              <div className="tip-approval-phase-copy">
                <p className="tip-approval-phase-title">
                  {phase.subtitle} — {phase.name}
                </p>
                <p className="tip-approval-phase-meta">
                  Timeline {phase.timeline} · One-time {formatCurrency(phase.oneTimeInvestment)}
                  {phase.monthlyRecurringInvestment > 0
                    ? ` · Monthly ${formatCurrency(phase.monthlyRecurringInvestment)}`
                    : ""}
                </p>
              </div>
              <div className="tip-approval-phase-sign">
                <div className="tip-signature-line tip-signature-line-compact" />
                <p className="tip-signature-label">Phase signature / date</p>
              </div>
            </div>
          ))}
        </div>

        <div className="tip-signature-line" />
        <p className="tip-signature-label">Authorized Signature</p>
        <div className="tip-signature-line" />
        <p className="tip-signature-label">Date</p>
      </div>
    </ReportSection>
  );
}

export function TipJourneyClosingSection({ data }: { data: TipReportData }) {
  const currentRating = getRating(data.currentScore);
  const projectedRating = getRating(data.projectedScore);
  const steps = ["Assess", "Improve", "Maintain"] as const;
  const activePhase = data.journeyPhaseLabel.toLowerCase();

  return (
    <>
      <ReportPageBreak />
      <ReportSection title="Your Technology Journey" documentTheme={DOCUMENT_THEME}>
        <div className="tip-closing-hero">
          <h3 className="tip-closing-hero-title">Assess → Improve → Maintain</h3>
          <p className="tip-closing-hero-subtitle">
            {BRAND.companyName} partners with organizations through Assess → Improve → Maintain to
            deliver measurable, lasting technology outcomes.
          </p>
          <div className="tip-closing-steps">
            {steps.map((step) => (
              <div key={step} className="tip-closing-step">
                <div
                  className={cn(
                    "tip-closing-step-dot",
                    activePhase.startsWith(step.toLowerCase().slice(0, 4)) &&
                      "tip-closing-step-dot-active",
                  )}
                />
                <p className="tip-closing-step-label">{step}</p>
              </div>
            ))}
          </div>
        </div>

        <div className="tip-closing-scores">
          <TipMaturityScoreMini
            label="Starting StackScore"
            score={data.currentScore}
            ratingLabel={RATING_LABELS[currentRating]}
          />
          <TipMaturityScoreMini
            label="Target StackScore"
            score={data.projectedScore}
            ratingLabel={RATING_LABELS[projectedRating]}
            projected
          />
        </div>

        <p className="mt-4 text-center text-xs text-[color:var(--report-muted)]">
          Generated by {BRAND.productName} on {data.generatedDate} · {BRAND.companyName} ·{" "}
          {BRAND.website}
        </p>
      </ReportSection>
    </>
  );
}

function TipMaturityScoreMini({
  label,
  score,
  ratingLabel,
  projected = false,
}: {
  label: string;
  score: number;
  ratingLabel: string;
  projected?: boolean;
}) {
  return (
    <div className={cn("tip-maturity-card", projected && "tip-maturity-card-projected")}>
      <p className="tip-maturity-card-label">{label}</p>
      <p className={cn("tip-maturity-card-score", getReportScoreTextClass(score))}>{score}</p>
      <p className="tip-maturity-card-rating">{ratingLabel}</p>
      <div className="tip-maturity-bar-track">
        <div
          className={cn("tip-maturity-bar-fill", getReportScoreBarClass(score))}
          style={{ width: `${Math.min(100, score)}%` }}
        />
      </div>
    </div>
  );
}

/** @deprecated Prefer TipCurrentMaturitySection — retained for any external imports */
export function TipPillarScorecardsSection({ data }: { data: TipReportData }) {
  return <TipCurrentMaturitySection data={data} />;
}

/** @deprecated Flat recommendation list replaced by phased initiative sections */
export function TipRecommendationsSection() {
  return null;
}

/** @deprecated Prefer TipRoadmapOverviewSection + TipPhaseDetailSections */
export function TipRoadmapSection({ data }: { data: TipReportData }) {
  return (
    <>
      <TipRoadmapOverviewSection data={data} />
      <TipPhaseDetailSections data={data} />
    </>
  );
}

/** @deprecated Prefer outcomes inside each phase */
export function TipBusinessOutcomesSection() {
  return null;
}
