"use client";

import { ArrowRight } from "lucide-react";
import { BRAND } from "@/lib/branding";
import { formatCurrency } from "@/lib/technology-improvement-plan/pricing";
import { getPriorityTimeline } from "@/lib/recommendations/display";
import { getRating, RATING_LABELS } from "@/lib/scoring";
import { getReportScoreBarClass, getReportScoreTextClass } from "@/lib/reports/document-score-display";
import {
  buildTipExecutiveFallback,
  getRoadmapPhaseObjectives,
  getRoadmapPhaseTimeline,
  TIP_MATURITY_TARGET,
} from "@/lib/reports/tip-presentation";
import type { TipReportData } from "@/lib/pdf/types";
import { ReportExecutiveSummary } from "@/components/reports/report-executive-summary";
import { ReportPageBreak, ReportPrintLeadGroup } from "@/components/reports";
import { ReportPriorityBadge } from "@/components/reports/report-priority-badge";
import { ReportSection } from "@/components/reports/report-section";
import { cn } from "@/lib/utils";
import { getReportTypeMeta } from "@/lib/reports/meta";

const DOCUMENT_THEME = true;

type TipReportCoverProps = {
  data: TipReportData;
};

export function TipReportCover({ data }: TipReportCoverProps) {
  const meta = getReportTypeMeta("technology_improvement_plan");

  return (
    <header className="tip-report-cover print:break-after-page">
      <p className="tip-report-cover-eyebrow">Generated by {BRAND.productName}</p>
      <h1 className="tip-report-cover-title">{meta.title}</h1>
      <p className="tip-report-cover-subtitle">{meta.subtitle}</p>

      <div className="tip-report-cover-meta">
        <div>
          <p className="tip-report-cover-meta-label">Prepared for</p>
          <p className="tip-report-cover-meta-value">{data.clientName}</p>
        </div>
        <div>
          <p className="tip-report-cover-meta-label">Document Version</p>
          <p className="tip-report-cover-meta-value">v{data.version}</p>
        </div>
        <div>
          <p className="tip-report-cover-meta-label">Prepared Date</p>
          <p className="tip-report-cover-meta-value">{data.generatedDate}</p>
        </div>
        {data.assessmentName ? (
          <div>
            <p className="tip-report-cover-meta-label">Based On Assessment</p>
            <p className="tip-report-cover-meta-value">{data.assessmentName}</p>
          </div>
        ) : data.maturityTierLabel ? (
          <div>
            <p className="tip-report-cover-meta-label">Current Maturity</p>
            <p className="tip-report-cover-meta-value">{data.maturityTierLabel}</p>
          </div>
        ) : null}
      </div>

      <p className="tip-report-cover-confidential">
        CONFIDENTIAL — This document contains proprietary analysis prepared exclusively for{" "}
        {data.clientName}. It may not be reproduced or distributed without written consent from{" "}
        {BRAND.companyName}.
      </p>
    </header>
  );
}

type TipMaturityHeroProps = {
  currentScore: number;
  projectedScore: number;
  scoreImprovement: number;
  journeyPhaseLabel: string;
  journeyProgressPercent: number;
};

export function TipMaturityHero({
  currentScore,
  projectedScore,
  scoreImprovement,
  journeyPhaseLabel,
  journeyProgressPercent,
}: TipMaturityHeroProps) {
  const currentRating = getRating(currentScore);
  const projectedRating = getRating(projectedScore);

  return (
    <div className="tip-maturity-hero">
      <h3 className="tip-maturity-hero-heading">Technology Maturity — Current vs Projected</h3>

      <div className="tip-maturity-compare">
        <div className="tip-maturity-card">
          <p className="tip-maturity-card-label">Today</p>
          <p className={cn("tip-maturity-card-score", getReportScoreTextClass(currentScore))}>
            {currentScore}
          </p>
          <p className="tip-maturity-card-rating">{RATING_LABELS[currentRating]}</p>
          <div className="tip-maturity-bar-track">
            <div
              className={cn("tip-maturity-bar-fill", getReportScoreBarClass(currentScore))}
              style={{ width: `${Math.min(100, currentScore)}%` }}
            />
          </div>
        </div>

        <div className="tip-maturity-delta" aria-hidden>
          <ArrowRight className="hidden h-5 w-5 text-[color:var(--report-muted)] md:block" />
          <p className="tip-maturity-delta-value">+{scoreImprovement}</p>
          <p className="tip-maturity-delta-label">StackScore points</p>
        </div>

        <div className="tip-maturity-card tip-maturity-card-projected">
          <p className="tip-maturity-card-label">Projected</p>
          <p className={cn("tip-maturity-card-score", getReportScoreTextClass(projectedScore))}>
            {projectedScore}
          </p>
          <p className="tip-maturity-card-rating">{RATING_LABELS[projectedRating]}</p>
          <div className="tip-maturity-bar-track">
            <div
              className={cn("tip-maturity-bar-fill", getReportScoreBarClass(projectedScore))}
              style={{ width: `${Math.min(100, projectedScore)}%` }}
            />
          </div>
        </div>
      </div>

      <div className="tip-journey-strip">
        <p className="tip-journey-strip-title">Technology Journey — {journeyPhaseLabel} Phase</p>
        <div className="tip-journey-strip-track">
          <div
            className="tip-journey-strip-fill"
            style={{ width: `${Math.min(100, journeyProgressPercent)}%` }}
          />
        </div>
        <p className="tip-journey-strip-meta">
          Journey progress: {journeyProgressPercent}% · Projected improvement: +{scoreImprovement}{" "}
          points · Maturity target: {TIP_MATURITY_TARGET}+
        </p>
      </div>
    </div>
  );
}

type TipExecutiveSummarySectionProps = {
  data: TipReportData;
  executiveSummary: string;
  isEditable?: boolean;
  onExecutiveSummaryChange?: (value: string) => void;
};

export function TipExecutiveSummarySection({
  data,
  executiveSummary,
  isEditable,
  onExecutiveSummaryChange,
}: TipExecutiveSummarySectionProps) {
  const fallback = buildTipExecutiveFallback(
    data.clientName,
    data.currentScore,
    data.projectedScore,
  );
  const paragraphs = (executiveSummary || fallback).trim().split(/\n\n+/).filter(Boolean);

  return (
    <ReportSection
      title="Executive Summary"
      subtitle="Business context, profile trajectory, and expected outcomes"
      documentTheme={DOCUMENT_THEME}
    >
      <ReportPrintLeadGroup>
        {isEditable && onExecutiveSummaryChange ? (
          <ReportExecutiveSummary
            value={executiveSummary}
            isEditable
            onChange={onExecutiveSummaryChange}
            fallback={fallback}
            className="tip-executive-prose min-h-32 rounded-lg border bg-[color:var(--report-background)] px-3 py-2"
          />
        ) : (
          <div className="tip-executive-prose-stack tip-executive-prose">
            {paragraphs.map((paragraph) => (
              <p key={paragraph.slice(0, 48)}>{paragraph}</p>
            ))}
          </div>
        )}
        <TipMaturityHero
          currentScore={data.currentScore}
          projectedScore={data.projectedScore}
          scoreImprovement={data.scoreImprovement}
          journeyPhaseLabel={data.journeyPhaseLabel}
          journeyProgressPercent={data.journeyProgressPercent}
        />
      </ReportPrintLeadGroup>
    </ReportSection>
  );
}

export function TipBusinessOutcomesSection({ data }: { data: TipReportData }) {
  if (data.businessOutcomes.length === 0) return null;

  return (
    <ReportSection
      title="Expected Business Outcomes"
      subtitle="Primary value drivers from prioritized initiatives"
      documentTheme={DOCUMENT_THEME}
    >
      <div className="tip-outcome-grid">
        {data.businessOutcomes.map((outcome, index) => (
          <article key={outcome.title} className="tip-outcome-card">
            <p className="tip-outcome-card-index">Outcome {index + 1}</p>
            <p className="tip-outcome-card-title">{outcome.title}</p>
            <p className="tip-outcome-card-body">{outcome.description}</p>
          </article>
        ))}
      </div>
    </ReportSection>
  );
}

export function TipPillarScorecardsSection({ data }: { data: TipReportData }) {
  if (data.categorySummaries.length === 0) return null;

  return (
    <ReportSection
      title="Technology Pillars"
      subtitle="Executive scorecard by domain — highlighted pillars include planned improvements"
      documentTheme={DOCUMENT_THEME}
    >
      <div className="tip-pillar-grid">
        {data.categorySummaries.map((category, index) => {
          const card = (
            <article
              key={category.name}
              className={cn(
                "tip-pillar-scorecard",
                category.hasRecommendations && "tip-pillar-scorecard-planned",
              )}
            >
              <div className="tip-pillar-scorecard-header">
                <p className="tip-pillar-scorecard-name">{category.name}</p>
                <p
                  className={cn(
                    "tip-pillar-scorecard-score",
                    getReportScoreTextClass(category.score),
                  )}
                >
                  {category.score}
                </p>
              </div>
              <p className="tip-pillar-scorecard-rating">{category.ratingLabel}</p>
              <div className="tip-pillar-scorecard-bar-track">
                <div
                  className={cn(
                    "tip-pillar-scorecard-bar-fill",
                    getReportScoreBarClass(category.score),
                  )}
                  style={{ width: `${Math.min(100, category.score)}%` }}
                />
              </div>
              <p className="tip-pillar-scorecard-foot">
                {category.hasRecommendations
                  ? "Improvement initiative planned in this domain"
                  : "Baseline maturity — no active initiatives in this plan"}
              </p>
              {category.hasRecommendations ? (
                <span className="tip-pillar-scorecard-badge">Improvement planned</span>
              ) : null}
            </article>
          );

          if (index === 0) {
            return <ReportPrintLeadGroup key={category.name}>{card}</ReportPrintLeadGroup>;
          }
          return card;
        })}
      </div>
    </ReportSection>
  );
}

export function TipRecommendationsSection({ data }: { data: TipReportData }) {
  return (
    <ReportSection
      title="Prioritized Recommendations"
      subtitle="Initiatives ordered by business impact and implementation priority"
      documentTheme={DOCUMENT_THEME}
    >
      <div className="tip-recommendation-list">
        {data.recommendations.map((rec, index) => {
          const card = (
            <article
              key={rec.id}
              className="tip-recommendation-card tip-recommendation-card-accent"
            >
              <div className="tip-recommendation-header">
                <p className="tip-recommendation-title">{rec.title}</p>
                <ReportPriorityBadge priority={rec.priority} documentTheme={DOCUMENT_THEME} />
              </div>
              <div className="tip-recommendation-meta-grid">
                <div className="tip-recommendation-meta-box">
                  <p className="tip-recommendation-meta-label">Expected Outcome</p>
                  <p className="tip-recommendation-meta-value">
                    +{rec.estimatedImpactPoints} StackScore pts
                  </p>
                </div>
                <div className="tip-recommendation-meta-box">
                  <p className="tip-recommendation-meta-label">Implementation Window</p>
                  <p className="tip-recommendation-meta-value">
                    {getPriorityTimeline(rec.priority)}
                  </p>
                </div>
                <div className="tip-recommendation-meta-box">
                  <p className="tip-recommendation-meta-label">Category</p>
                  <p className="tip-recommendation-meta-value">{rec.categoryName}</p>
                </div>
              </div>
              <div className="tip-recommendation-body">
                <p className="tip-recommendation-field-label">Business Impact</p>
                <p className="tip-recommendation-field-value">{rec.businessImpact}</p>
                {rec.suggestedService ? (
                  <>
                    <p className="tip-recommendation-field-label mt-3">Recommended Service</p>
                    <p className="tip-recommendation-field-value">{rec.suggestedService}</p>
                  </>
                ) : null}
                {rec.executiveNote ? (
                  <>
                    <p className="tip-recommendation-field-label mt-3">Executive Note</p>
                    <p className="tip-recommendation-field-value">{rec.executiveNote}</p>
                  </>
                ) : null}
              </div>
            </article>
          );

          if (index === 0) {
            return <ReportPrintLeadGroup key={rec.id}>{card}</ReportPrintLeadGroup>;
          }
          return card;
        })}
      </div>
    </ReportSection>
  );
}

export function TipRoadmapSection({ data }: { data: TipReportData }) {
  return (
    <ReportSection
      title="Phased Implementation Roadmap"
      subtitle="Sequential delivery plan with projected profile progression and business objectives"
      documentTheme={DOCUMENT_THEME}
    >
      <div className="tip-roadmap-timeline">
        {data.roadmapPhases.map((phase, index) => {
          const objectives = getRoadmapPhaseObjectives(phase);
          const timeline = getRoadmapPhaseTimeline(phase);
          const isActive = index === 0;

          return (
            <div key={phase.id} className="tip-roadmap-phase">
              <div className="tip-roadmap-phase-rail">
                <div
                  className={cn(
                    "tip-roadmap-phase-dot",
                    isActive && "tip-roadmap-phase-dot-active",
                  )}
                >
                  {index + 1}
                </div>
                {index < data.roadmapPhases.length - 1 ? (
                  <div className="tip-roadmap-phase-line" aria-hidden />
                ) : null}
              </div>

              <article
                className={cn(
                  "tip-roadmap-phase-card",
                  isActive && "tip-roadmap-phase-card-active",
                )}
              >
                <div className="tip-roadmap-phase-header">
                  <div>
                    <p className="tip-roadmap-phase-label">{phase.label}</p>
                    <p className="tip-roadmap-phase-timeline">{timeline}</p>
                  </div>
                  <div className="tip-roadmap-phase-score-block">
                    <p
                      className={cn(
                        "tip-roadmap-phase-score",
                        getReportScoreTextClass(phase.projectedScore),
                      )}
                    >
                      {phase.projectedScore}
                    </p>
                    <p className="tip-roadmap-phase-delta">+{phase.scoreDelta} points</p>
                  </div>
                </div>

                <ul className="tip-roadmap-initiatives">
                  {phase.recommendations.map((rec) => (
                    <li key={rec.id}>{rec.title}</li>
                  ))}
                </ul>

                {objectives.length > 0 ? (
                  <div className="tip-roadmap-objectives">
                    <p className="tip-roadmap-objectives-label">Business objectives</p>
                    <ul className="tip-roadmap-objectives-list">
                      {objectives.map((objective) => (
                        <li key={objective.slice(0, 48)}>{objective}</li>
                      ))}
                    </ul>
                  </div>
                ) : null}
              </article>
            </div>
          );
        })}
      </div>
    </ReportSection>
  );
}

type TipInvestmentSectionProps = {
  data: TipReportData;
  isAdmin?: boolean;
};

export function TipInvestmentSection({ data, isAdmin = false }: TipInvestmentSectionProps) {
  return (
    <ReportSection
      title="Investment Summary"
      subtitle="Professional services and technology investment required to execute this plan"
      documentTheme={DOCUMENT_THEME}
    >
      <div className="tip-investment-table">
        <div className="tip-investment-table-head">
          <span>Category</span>
          <span>Description</span>
          <span className="text-right">Amount</span>
        </div>
        {data.investmentLineItems.map((row, index) => (
          <div
            key={row.category}
            className={cn(
              "tip-investment-table-row",
              index % 2 === 1 && "tip-investment-table-row-alt",
            )}
          >
            <span className="tip-investment-table-category">{row.category}</span>
            <span className="tip-investment-table-desc">{row.description}</span>
            <span className="tip-investment-table-amount">{formatCurrency(row.amount)}</span>
          </div>
        ))}
      </div>

      <div className="tip-investment-total">
        <p className="tip-investment-total-label">Total Client Investment</p>
        <p className="tip-investment-total-value">{formatCurrency(data.clientInvestmentTotal)}</p>
        <p className="tip-investment-total-caption">
          All professional services, technology, and implementation costs required to execute this
          improvement plan.
        </p>
      </div>

      {isAdmin && data.investmentBreakdown ? (
        <div className="mt-4 rounded-lg border border-dashed border-amber-300 bg-amber-50/80 p-4 print:hidden">
          <p className="text-xs font-semibold uppercase tracking-wide text-amber-800">
            Internal Pricing (Admin Only — not in client PDF)
          </p>
          <div className="mt-2 grid gap-2 text-sm text-amber-950 sm:grid-cols-2">
            <p>Margin: {data.investmentBreakdown.marginPercent}%</p>
            <p>Margin amount: {formatCurrency(data.investmentBreakdown.marginAmount)}</p>
            <p>Labor: {formatCurrency(data.investmentBreakdown.labor)}</p>
            <p>Hardware: {formatCurrency(data.investmentBreakdown.hardware)}</p>
          </div>
        </div>
      ) : null}
    </ReportSection>
  );
}

export function TipApprovalSection({ clientName }: { clientName: string }) {
  return (
    <ReportSection
      title="Approval"
      subtitle="Authorization to proceed with the initiatives outlined in this plan"
      documentTheme={DOCUMENT_THEME}
    >
      <div className="tip-approval-block">
        <p className="tip-executive-prose">
          By signing below, {clientName} acknowledges review of this Technology Improvement Plan
          and approves the proposed initiatives and investment summarized above.
        </p>
        <div className="tip-signature-line" />
        <p className="tip-signature-label">Authorized Signature</p>
        <div className="tip-signature-line" />
        <p className="tip-signature-label">Date</p>
      </div>
    </ReportSection>
  );
}

export function TipJourneyClosingSection({ data }: { data: TipReportData }) {
  const currentRating = getRating(data.currentScore);
  const projectedRating = getRating(data.projectedScore);
  const steps = ["Assess", "Improve", "Maintain"] as const;
  const activePhase = data.journeyPhaseLabel.toLowerCase();

  return (
    <>
      <ReportPageBreak />
      <ReportSection title="Your Technology Journey" documentTheme={DOCUMENT_THEME}>
        <div className="tip-closing-hero">
          <h3 className="tip-closing-hero-title">Assess → Improve → Maintain</h3>
          <p className="tip-closing-hero-subtitle">
            {BRAND.companyName} partners with organizations through Assess → Improve → Maintain to
            deliver measurable, lasting technology outcomes.
          </p>
          <div className="tip-closing-steps">
            {steps.map((step) => (
              <div key={step} className="tip-closing-step">
                <div
                  className={cn(
                    "tip-closing-step-dot",
                    activePhase.startsWith(step.toLowerCase().slice(0, 4)) &&
                      "tip-closing-step-dot-active",
                  )}
                />
                <p className="tip-closing-step-label">{step}</p>
              </div>
            ))}
          </div>
        </div>

        <div className="tip-closing-scores">
          <TipMaturityScoreMini
            label="Starting StackScore"
            score={data.currentScore}
            ratingLabel={RATING_LABELS[currentRating]}
          />
          <TipMaturityScoreMini
            label="Target StackScore"
            score={data.projectedScore}
            ratingLabel={RATING_LABELS[projectedRating]}
            projected
          />
        </div>

        <p className="mt-4 text-center text-xs text-[color:var(--report-muted)]">
          Generated by {BRAND.productName} on {data.generatedDate} · {BRAND.companyName} ·{" "}
          {BRAND.website}
        </p>
      </ReportSection>
    </>
  );
}

function TipMaturityScoreMini({
  label,
  score,
  ratingLabel,
  projected = false,
}: {
  label: string;
  score: number;
  ratingLabel: string;
  projected?: boolean;
}) {
  return (
    <div className={cn("tip-maturity-card", projected && "tip-maturity-card-projected")}>
      <p className="tip-maturity-card-label">{label}</p>
      <p className={cn("tip-maturity-card-score", getReportScoreTextClass(score))}>{score}</p>
      <p className="tip-maturity-card-rating">{ratingLabel}</p>
      <div className="tip-maturity-bar-track">
        <div
          className={cn("tip-maturity-bar-fill", getReportScoreBarClass(score))}
          style={{ width: `${Math.min(100, score)}%` }}
        />
      </div>
    </div>
  );
}
