import { northstarManufacturing } from "@/lib/product-overview/demo-organization";
import {
  DEMO_RECOMMENDATIONS,
  DEMO_ROADMAP_INITIATIVES,
} from "@/lib/product-overview/demo-strategy";
import { STANDARD_TIMELINE } from "@/lib/product-overview/demo-execution";
import type { DemoDashboard } from "@/lib/product-overview/types";

export { getDemoRecommendationById } from "@/lib/product-overview/demo-strategy";

export const featuredRecommendation = DEMO_RECOMMENDATIONS[0]!;

export const northstarDemoDashboard: DemoDashboard = {
  organization: northstarManufacturing,
  technologyScore: {
    score: 68,
    maxScore: 100,
    maturityLabel: "Developing",
    changeSinceLastReview: 6,
    projectedScore: 82,
    projectedMaturityLabel: "Managed",
    projectedNote: "Projected score reflects completion of the current approved roadmap.",
  },
  metrics: {
    openRecommendations: 14,
    highPriorityRecommendations: 5,
    quickWins: 4,
    plannedThisQuarter: 3,
    activeProjects: 4,
    roadmapCompletionPercent: 42,
    annualTechnologyPlan: 48_000,
    approvedSpend: 30_000,
  },
  pillars: [
    {
      id: "strategy-governance",
      name: "Strategy & Governance",
      score: 72,
      maturityLabel: "Defined",
      summary: "Technology planning exists but needs stronger executive alignment and quarterly accountability.",
      primaryRisk: "Roadmap priorities are not consistently tied to business outcomes.",
      exampleRecommendation: "Establish a quarterly technology steering committee with executive sponsors.",
      targetScore: 84,
      businessImpact: "Improves decision velocity and keeps investments aligned with growth goals.",
      trend: "up",
      trendDelta: 4,
      keyFinding: "Technology priorities exist but lack consistent executive sponsorship.",
      priorityLevel: "Medium",
      recommendedImprovement: "Establish a quarterly technology steering committee with executive sponsors.",
      expectedBusinessOutcome: "Improves decision velocity and keeps investments aligned with growth goals.",
      statusColor: "success",
      linkedRecommendationId: "rec-governance-committee",
      linkedRoadmapInitiativeId: "roadmap-governance-refresh",
    },
    {
      id: "infrastructure",
      name: "Infrastructure",
      score: 61,
      maturityLabel: "Developing",
      summary: "Core systems are stable, but aging network equipment is creating capacity and reliability pressure.",
      primaryRisk: "Ubiquiti switching and Wi-Fi are beyond recommended lifecycle.",
      exampleRecommendation: "Modernize Ubiquiti switching and Wi-Fi at the production site.",
      targetScore: 80,
      businessImpact: "Reduces downtime risk and supports modern security controls.",
      trend: "stable",
      trendDelta: 0,
      keyFinding: "Ubiquiti switching and Wi-Fi are beyond recommended lifecycle.",
      priorityLevel: "High",
      recommendedImprovement: "Modernize Ubiquiti switches and Wi-Fi at the single production site.",
      expectedBusinessOutcome: "Reduces downtime risk with right-sized networking for production systems.",
      statusColor: "warning",
      linkedRecommendationId: "rec-network-switches",
      linkedRoadmapInitiativeId: "roadmap-network-refresh",
    },
    {
      id: "cybersecurity",
      name: "Cybersecurity",
      score: 58,
      maturityLabel: "Developing",
      summary: "Baseline protections are in place, but identity and monitoring coverage remain inconsistent.",
      primaryRisk: "Inconsistent identity protection and limited security monitoring.",
      exampleRecommendation: "Harden MFA on Microsoft 365 Business Premium for privileged accounts.",
      targetScore: 78,
      businessImpact: "Reduces account compromise risk and strengthens cyber-insurance readiness.",
      trend: "up",
      trendDelta: 3,
      keyFinding: "Multi-factor authentication is inconsistently enforced across privileged accounts.",
      priorityLevel: "Critical",
      recommendedImprovement: "Harden MFA and privileged access controls on Microsoft 365 Business Premium.",
      expectedBusinessOutcome: "Reduced cyber risk and stronger cyber insurance readiness.",
      statusColor: "critical",
      linkedRecommendationId: "rec-mfa",
      linkedRoadmapInitiativeId: "roadmap-m365-hardening",
    },
    {
      id: "business-continuity",
      name: "Business Continuity",
      score: 55,
      maturityLabel: "Developing",
      summary: "Backup jobs run regularly, but validation and recovery testing are not standardized.",
      primaryRisk: "Recovery readiness is difficult to prove during audits or incidents.",
      exampleRecommendation: "Implement centralized backup validation with documented recovery tests.",
      targetScore: 76,
      businessImpact: "Improves resilience and reduces operational disruption during outages.",
      trend: "up",
      trendDelta: 2,
      keyFinding: "Backups run regularly but validation and recovery testing are not standardized.",
      priorityLevel: "High",
      recommendedImprovement: "Implement centralized backup validation with documented recovery tests.",
      expectedBusinessOutcome: "Improves resilience and reduces operational disruption during outages.",
      statusColor: "warning",
      linkedRecommendationId: "rec-backup-validation",
      linkedRoadmapInitiativeId: "roadmap-backup-validation",
    },
    {
      id: "applications-data",
      name: "Applications & Data",
      score: 70,
      maturityLabel: "Defined",
      summary: "Microsoft 365 adoption is strong, but data ownership and lifecycle policies need refinement.",
      primaryRisk: "Sensitive operational data lacks consistent retention and access controls.",
      exampleRecommendation: "Define data classification and retention policies for manufacturing systems.",
      targetScore: 82,
      businessImpact: "Supports compliance readiness and cleaner collaboration workflows.",
      trend: "up",
      trendDelta: 5,
      keyFinding: "Sensitive operational data lacks consistent retention and access controls.",
      priorityLevel: "Medium",
      recommendedImprovement: "Define data classification and retention policies for manufacturing systems.",
      expectedBusinessOutcome: "Supports compliance readiness and cleaner collaboration workflows.",
      statusColor: "success",
      linkedRecommendationId: "rec-data-classification",
      linkedRoadmapInitiativeId: "roadmap-app-review",
    },
    {
      id: "operations-support",
      name: "Operations & Support",
      score: 74,
      maturityLabel: "Defined",
      summary: "Support processes are responsive, though documentation and escalation paths could be clearer.",
      primaryRisk: "Troubleshooting relies on tribal knowledge during shift changes.",
      exampleRecommendation: "Standardize incident response playbooks for production systems.",
      targetScore: 85,
      businessImpact: "Shortens resolution time and improves service consistency.",
      trend: "up",
      trendDelta: 2,
      keyFinding: "Troubleshooting relies on tribal knowledge during shift changes.",
      priorityLevel: "Medium",
      recommendedImprovement: "Standardize incident response playbooks for production systems.",
      expectedBusinessOutcome: "Shortens resolution time and improves service consistency.",
      statusColor: "success",
      linkedRecommendationId: "rec-endpoint-lifecycle",
      linkedRoadmapInitiativeId: "roadmap-endpoint-lifecycle",
    },
    {
      id: "people-process",
      name: "People & Process",
      score: 66,
      maturityLabel: "Developing",
      summary: "Teams adopt new tools quickly, but security and change-management training is uneven.",
      primaryRisk: "Process adherence varies across departments and shifts.",
      exampleRecommendation: "Launch role-based security awareness training for plant and office staff.",
      targetScore: 79,
      businessImpact: "Reduces human-factor risk and improves change adoption.",
      trend: "stable",
      trendDelta: 0,
      keyFinding: "Device replacement and patching policies vary across departments and shifts.",
      priorityLevel: "Medium",
      recommendedImprovement: "Standardize endpoint lifecycle and role-based security awareness training.",
      expectedBusinessOutcome: "Reduces security gaps from aging endpoints and inconsistent patching.",
      statusColor: "neutral",
      linkedRecommendationId: "rec-endpoint-lifecycle",
      linkedRoadmapInitiativeId: "roadmap-endpoint-lifecycle",
    },
    {
      id: "digital-enablement",
      name: "Digital Enablement",
      score: 76,
      maturityLabel: "Defined",
      summary: "Digital tools support daily operations, with room to connect shop-floor and leadership reporting.",
      primaryRisk: "Operational reporting still requires manual consolidation.",
      exampleRecommendation: "Connect production metrics to executive dashboards in StackScore.",
      targetScore: 86,
      businessImpact: "Improves visibility for leadership and accelerates operational decisions.",
      trend: "up",
      trendDelta: 6,
      keyFinding: "Operational reporting still requires manual consolidation.",
      priorityLevel: "Low",
      recommendedImprovement: "Connect production metrics to executive dashboards in StackScore.",
      expectedBusinessOutcome: "Improves visibility for leadership and accelerates operational decisions.",
      statusColor: "success",
      linkedRecommendationId: "rec-governance-committee",
      linkedRoadmapInitiativeId: "roadmap-governance-refresh",
    },
  ],
  recommendations: DEMO_RECOMMENDATIONS,
  featuredRecommendationId: featuredRecommendation.id,
  projects: [
    {
      id: "proj-m365-hardening",
      title: "Microsoft 365 Security Hardening",
      status: "In Progress",
      progress: 68,
      owner: "Jordan Ellis",
      targetCompletion: "August 28, 2026",
      description:
        "Hardening Microsoft 365 Business Premium identity, conditional access, and privileged account protections for Northstar's single location.",
      milestones: [
        "Conditional access baseline deployed",
        "Privileged account MFA enforcement",
        "Legacy authentication blocked",
        "Security policy documentation finalized",
      ],
      relatedRecommendation: "Harden MFA on Microsoft 365 Business Premium",
      businessOutcome: "Closes the highest-priority identity risk before Ubiquiti network modernization begins.",
      budgetRange: "$2,000–$4,000",
      priority: "Critical",
      pillarId: "cybersecurity",
      pillarName: "Cybersecurity",
      relatedRecommendationId: "rec-mfa",
      relatedRoadmapInitiativeId: "roadmap-m365-hardening",
      relatedQuarterlyReviewId: "qbr-q3-2026",
      businessObjective: "Eliminate the highest-priority identity risk before infrastructure refresh begins.",
      timelinePhases: STANDARD_TIMELINE,
      currentRisks: [
        "Two legacy service accounts still exempt from MFA enforcement",
        "Conditional access policy exceptions require executive review",
      ],
      dependencies: ["Privileged account inventory", "Conditional access baseline"],
      projectNotes: [
        "Executive sponsor confirmed identity protection as Q3 priority.",
        "Plant floor kiosk accounts excluded from MFA per operational requirements.",
      ],
    },
    {
      id: "proj-network-refresh",
      title: "Network Infrastructure Refresh",
      status: "Planning",
      progress: 22,
      owner: "Jordan Ellis",
      targetCompletion: "November 14, 2026",
      description:
        "Upgrade aging Ubiquiti switches and Wi-Fi to improve reliability, coverage, and segmentation without enterprise chassis spend.",
      milestones: [
        "Site survey completed",
        "Hardware standards approved",
        "Implementation schedule confirmed",
      ],
      relatedRecommendation: "Modernize Ubiquiti Switching & Wi-Fi",
      businessOutcome: "Delivers reliable business-grade connectivity at an SMB-appropriate investment level.",
      budgetRange: "$6,000–$10,000",
      priority: "High",
      pillarId: "infrastructure",
      pillarName: "Infrastructure",
      relatedRecommendationId: "rec-network-switches",
      relatedRoadmapInitiativeId: "roadmap-network-refresh",
      relatedQuarterlyReviewId: "qbr-q3-2026",
      businessObjective: "Modernize aging network infrastructure to reduce downtime and support security segmentation.",
      timelinePhases: [
        { id: "planning", label: "Planning", status: "current" },
        { id: "assessment", label: "Assessment Complete", status: "completed" },
        { id: "approved-rec", label: "Recommendation Approved", status: "completed" },
        { id: "budget", label: "Budget Approved", status: "completed" },
        { id: "implementation", label: "Implementation", status: "upcoming" },
        { id: "validation", label: "Validation", status: "upcoming" },
        { id: "completed", label: "Completed", status: "upcoming" },
      ],
      currentRisks: [
        "Production downtime window not yet confirmed with plant operations",
        "Hardware lead times may push implementation into Q1 2027",
      ],
      dependencies: ["Microsoft 365 Security Hardening completion", "Site survey sign-off"],
      projectNotes: [
        "Scheduled to begin after identity protection project reaches validation phase.",
        "Vendor quotes received; executive approval pending.",
      ],
    },
    {
      id: "proj-backup-validation",
      title: "Disaster Recovery Validation",
      status: "On Track",
      progress: 41,
      owner: "Morgan Lee",
      targetCompletion: "October 3, 2026",
      description:
        "Stand up practical backup monitoring, validation, and quarterly recovery testing for critical business systems.",
      milestones: [
        "Backup inventory completed",
        "Validation workflow designed",
        "First recovery test scheduled",
      ],
      relatedRecommendation: featuredRecommendation.title,
      businessOutcome: "Provides auditable proof of recovery readiness without oversized DR platforms.",
      budgetRange: "$3,500–$6,500",
      priority: "High",
      pillarId: "business-continuity",
      pillarName: "Business Continuity",
      relatedRecommendationId: "rec-backup-validation",
      relatedRoadmapInitiativeId: "roadmap-backup-validation",
      relatedQuarterlyReviewId: "qbr-q3-2026",
      businessObjective: "Prove recovery readiness with standardized backup validation and documented testing.",
      timelinePhases: [
        { id: "planning", label: "Planning", status: "completed" },
        { id: "assessment", label: "Assessment Complete", status: "completed" },
        { id: "approved-rec", label: "Recommendation Approved", status: "completed" },
        { id: "budget", label: "Budget Approved", status: "completed" },
        { id: "implementation", label: "Implementation", status: "current" },
        { id: "validation", label: "Validation", status: "upcoming" },
        { id: "completed", label: "Completed", status: "upcoming" },
      ],
      currentRisks: [
        "Manufacturing system backup coverage gaps identified during inventory",
        "Recovery test scheduling requires coordination with production downtime",
      ],
      dependencies: ["Backup inventory", "Validation workflow design"],
      projectNotes: [
        "First recovery test scheduled for October with executive observer.",
        "Cyber insurance renewal requires proof of validation by Q4.",
      ],
    },
    {
      id: "proj-policy-standardization",
      title: "Technology Policy Standardization",
      status: "In Progress",
      progress: 54,
      owner: "Morgan Lee",
      targetCompletion: "September 19, 2026",
      description:
        "Standardize acceptable use, device lifecycle, and vendor management policies for Northstar's single-site operations.",
      milestones: [
        "Policy gap analysis completed",
        "Executive review scheduled",
        "Employee communication drafted",
      ],
      relatedRecommendation: "Define Data Classification Policies",
      businessOutcome: "Creates consistent expectations and reduces compliance gaps at a practical consulting cost.",
      budgetRange: "$1,000–$2,000",
      priority: "Medium",
      pillarId: "applications-data",
      pillarName: "Applications & Data",
      relatedRecommendationId: "rec-data-classification",
      relatedRoadmapInitiativeId: "roadmap-app-review",
      relatedQuarterlyReviewId: "qbr-q3-2026",
      businessObjective: "Establish consistent technology policies that support compliance and operational clarity.",
      timelinePhases: [
        { id: "planning", label: "Planning", status: "completed" },
        { id: "assessment", label: "Assessment Complete", status: "completed" },
        { id: "approved-rec", label: "Recommendation Approved", status: "completed" },
        { id: "budget", label: "Budget Approved", status: "completed" },
        { id: "implementation", label: "Implementation", status: "current" },
        { id: "validation", label: "Validation", status: "upcoming" },
        { id: "completed", label: "Completed", status: "upcoming" },
      ],
      currentRisks: [
        "Plant shift supervisors need additional policy training before rollout",
        "Vendor management policy requires legal review",
      ],
      dependencies: ["Data classification framework", "Executive review scheduling"],
      projectNotes: [
        "Employee communication draft ready for HR and legal review.",
        "Policy rollout planned for October after executive sign-off.",
      ],
    },
  ],
  roadmapQuarters: [
    {
      quarter: "Q3 2026",
      items: [
        "Microsoft 365 security hardening",
        "Device lifecycle policy",
        "Backup validation design",
      ],
    },
    {
      quarter: "Q4 2026",
      items: ["Ubiquiti network refresh", "Disaster recovery exercise", "Vendor inventory cleanup"],
    },
    {
      quarter: "Q1 2027",
      items: ["Application review", "Identity lifecycle improvements"],
    },
  ],
  roadmapInitiatives: DEMO_ROADMAP_INITIATIVES,
  quarterlyReview: {
    nextReviewDate: "September 15, 2026",
    status: "Preparation in progress",
    scoreChange: 6,
    projectsCompleted: 2,
    recommendationsClosed: 5,
    budgetVariance: "3% under plan",
    currentScore: 68,
    previousScore: 62,
    openHighPriority: 3,
    roadmapCompletionPercent: 42,
    budgetUtilizationPercent: 63,
    executiveSummary: [
      "Technology score improved 6 points since the last quarterly review.",
      "Two strategic projects completed on schedule with measurable risk reduction.",
      "Five recommendations were closed, including quick wins in identity and policy standardization.",
      "Technology spending remains disciplined against a $48,000 annual plan — spend smarter, not more.",
    ],
  },
  budget: {
    planned: 48_000,
    approved: 30_000,
    committed: 18_000,
    remaining: 12_000,
  },
  nextAction: {
    title: "Complete Microsoft 365 Security Hardening before starting the Ubiquiti network refresh.",
    body: "Complete Microsoft 365 Security Hardening before starting the Ubiquiti network refresh.",
    reason:
      "This closes the highest-priority identity risk and keeps the quarterly investment plan on track.",
    relatedProjectId: "proj-m365-hardening",
    relatedRecommendationId: "rec-mfa",
  },
};

export function getDemoPillarById(id: string) {
  return northstarDemoDashboard.pillars.find((pillar) => pillar.id === id);
}

export function getDemoProjectById(id: string) {
  return northstarDemoDashboard.projects.find((project) => project.id === id);
}

export function formatDemoCurrency(value: number) {
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
    maximumFractionDigits: 0,
  }).format(value);
}
